# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/futures/tests/regressions
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/futures/tests/regressions
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.regressions.modules.futures.exception_from_continuation_1613 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/exception_from_continuation_1613_test" "-e" "0" "-t" "2" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.futures.exception_from_continuation_1613 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/futures/tests/regressions/CMakeLists.txt;36;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/futures/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.futures.future_2667 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/future_2667_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.futures.future_2667 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/futures/tests/regressions/CMakeLists.txt;36;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/futures/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.futures.future_790 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/future_790_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.futures.future_790 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/futures/tests/regressions/CMakeLists.txt;36;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/futures/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.futures.future_unwrap_878 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/future_unwrap_878_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.futures.future_unwrap_878 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/futures/tests/regressions/CMakeLists.txt;36;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/futures/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.futures.future_unwrap_1182 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/future_unwrap_1182_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.futures.future_unwrap_1182 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/futures/tests/regressions/CMakeLists.txt;36;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/futures/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.futures.set_hpx_limit_798 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/set_hpx_limit_798_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.futures.set_hpx_limit_798 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/futures/tests/regressions/CMakeLists.txt;36;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/futures/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.futures.shared_future_continuation_order "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/shared_future_continuation_order_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.futures.shared_future_continuation_order PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/futures/tests/regressions/CMakeLists.txt;36;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/futures/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.futures.shared_future_then_2166 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/shared_future_then_2166_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.futures.shared_future_then_2166 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/futures/tests/regressions/CMakeLists.txt;36;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/futures/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.futures.wait_for_1751 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/wait_for_1751_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.futures.wait_for_1751 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/futures/tests/regressions/CMakeLists.txt;36;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/futures/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.futures.future_range_ambiguity_2032 "/opt/homebrew/bin/cmake" "--build" "/Users/harith/Desktop/Open Source/hpx/build2" "--target" "tests_regressions_modules_futures_future_range_ambiguity_2032" "--config" "Release")
set_tests_properties(tests.regressions.modules.futures.future_range_ambiguity_2032 PROPERTIES  RUN_SERIAL "TRUE" WORKING_DIRECTORY "/Users/harith/Desktop/Open Source/hpx/build2" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;48;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;74;add_hpx_compile_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;86;add_test_and_deps_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/core/futures/tests/regressions/CMakeLists.txt;57;add_hpx_regression_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/core/futures/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.futures.fail_future_2667 "/opt/homebrew/bin/cmake" "--build" "/Users/harith/Desktop/Open Source/hpx/build2" "--target" "tests_regressions_modules_futures_fail_future_2667" "--config" "Release")
set_tests_properties(tests.regressions.modules.futures.fail_future_2667 PROPERTIES  RUN_SERIAL "TRUE" WILL_FAIL "TRUE" WORKING_DIRECTORY "/Users/harith/Desktop/Open Source/hpx/build2" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;48;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;74;add_hpx_compile_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;86;add_test_and_deps_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/core/futures/tests/regressions/CMakeLists.txt;57;add_hpx_regression_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/core/futures/tests/regressions/CMakeLists.txt;0;")
