# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/full/init_runtime/tests/unit
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/full/init_runtime/tests/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.unit.modules.init_runtime.runtime_type "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/runtime_type_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.init_runtime.runtime_type PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/init_runtime/tests/unit/CMakeLists.txt;35;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/init_runtime/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.init_runtime.parcel_pool "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/parcel_pool_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.init_runtime.parcel_pool PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/init_runtime/tests/unit/CMakeLists.txt;35;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/init_runtime/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.init_runtime.shutdown_suspended_thread "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/shutdown_suspended_thread_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.init_runtime.shutdown_suspended_thread PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/init_runtime/tests/unit/CMakeLists.txt;35;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/init_runtime/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.init_runtime.start_stop_callbacks "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/start_stop_callbacks_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.init_runtime.start_stop_callbacks PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/init_runtime/tests/unit/CMakeLists.txt;35;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/init_runtime/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.init_runtime.handled_exception "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/handled_exception_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.init_runtime.handled_exception PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/init_runtime/tests/unit/CMakeLists.txt;35;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/init_runtime/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.init_runtime.unhandled_exception "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/unhandled_exception_test" "-e" "1" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.init_runtime.unhandled_exception PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/init_runtime/tests/unit/CMakeLists.txt;35;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/init_runtime/tests/unit/CMakeLists.txt;0;")
