# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/full/resiliency_distributed/tests/unit
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/full/resiliency_distributed/tests/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.unit.modules.resiliency_distributed.distributed.tcp.async_replay_distributed_plain "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_replay_distributed_plain_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.unit.modules.resiliency_distributed.distributed.tcp.async_replay_distributed_plain PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/resiliency_distributed/tests/unit/CMakeLists.txt;32;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/resiliency_distributed/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.resiliency_distributed.distributed.tcp.async_replicate_distributed_plain "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_replicate_distributed_plain_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.unit.modules.resiliency_distributed.distributed.tcp.async_replicate_distributed_plain PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/resiliency_distributed/tests/unit/CMakeLists.txt;32;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/resiliency_distributed/tests/unit/CMakeLists.txt;0;")
