# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replicate
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/resiliency/tests/performance/replicate
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.performance.modules.resiliency.replicate.async_replicate "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_replicate_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.performance.modules.resiliency.replicate.async_replicate PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;286;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replicate/CMakeLists.txt;35;add_hpx_performance_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replicate/CMakeLists.txt;0;")
add_test(tests.performance.modules.resiliency.replicate.async_replicate_validate "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_replicate_validate_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.performance.modules.resiliency.replicate.async_replicate_validate PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;286;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replicate/CMakeLists.txt;35;add_hpx_performance_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replicate/CMakeLists.txt;0;")
add_test(tests.performance.modules.resiliency.replicate.async_replicate_vote "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_replicate_vote_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.performance.modules.resiliency.replicate.async_replicate_vote PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;286;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replicate/CMakeLists.txt;35;add_hpx_performance_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replicate/CMakeLists.txt;0;")
add_test(tests.performance.modules.resiliency.replicate.async_replicate_vote_validate "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_replicate_vote_validate_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.performance.modules.resiliency.replicate.async_replicate_vote_validate PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;286;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replicate/CMakeLists.txt;35;add_hpx_performance_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replicate/CMakeLists.txt;0;")
add_test(tests.performance.modules.resiliency.replicate.pure_async_for_replicate "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/pure_async_for_replicate_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.performance.modules.resiliency.replicate.pure_async_for_replicate PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;286;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replicate/CMakeLists.txt;35;add_hpx_performance_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replicate/CMakeLists.txt;0;")
add_test(tests.performance.modules.resiliency.replicate.1d_stencil_replicate "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/1d_stencil_replicate_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.performance.modules.resiliency.replicate.1d_stencil_replicate PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;286;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replicate/CMakeLists.txt;35;add_hpx_performance_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replicate/CMakeLists.txt;0;")
add_test(tests.performance.modules.resiliency.replicate.1d_stencil_replicate_checksum "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/1d_stencil_replicate_checksum_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.performance.modules.resiliency.replicate.1d_stencil_replicate_checksum PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;286;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replicate/CMakeLists.txt;35;add_hpx_performance_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replicate/CMakeLists.txt;0;")
