# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/regressions
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/serialization/tests/regressions
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.regressions.modules.serialization.buffer_overrun_2839 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/buffer_overrun_2839_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.serialization.buffer_overrun_2839 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/regressions/CMakeLists.txt;26;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.serialization.non_default_constructible_5886 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/non_default_constructible_5886_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.serialization.non_default_constructible_5886 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/regressions/CMakeLists.txt;26;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.serialization.not_bitwise_shared_ptr_serialization "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/not_bitwise_shared_ptr_serialization_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.serialization.not_bitwise_shared_ptr_serialization PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/regressions/CMakeLists.txt;26;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.serialization.serialization_unsigned_buffer "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/serialization_unsigned_buffer_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.serialization.serialization_unsigned_buffer PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/regressions/CMakeLists.txt;26;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.serialization.std_variant_4448 "/opt/homebrew/bin/cmake" "--build" "/Users/harith/Desktop/Open Source/hpx/build2" "--target" "tests_regressions_modules_serialization_std_variant_4448" "--config" "Release")
set_tests_properties(tests.regressions.modules.serialization.std_variant_4448 PROPERTIES  RUN_SERIAL "TRUE" WORKING_DIRECTORY "/Users/harith/Desktop/Open Source/hpx/build2" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;48;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;74;add_hpx_compile_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;86;add_test_and_deps_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/regressions/CMakeLists.txt;49;add_hpx_regression_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/regressions/CMakeLists.txt;0;")
