# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/full
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/full
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("actions")
subdirs("actions_base")
subdirs("agas")
subdirs("agas_base")
subdirs("async_colocated")
subdirs("async_distributed")
subdirs("checkpoint")
subdirs("checkpoint_base")
subdirs("collectives")
subdirs("command_line_handling")
subdirs("components")
subdirs("components_base")
subdirs("compute")
subdirs("distribution_policies")
subdirs("executors_distributed")
subdirs("include")
subdirs("init_runtime")
subdirs("lcos_distributed")
subdirs("naming")
subdirs("naming_base")
subdirs("parcelport_gasnet")
subdirs("parcelport_lci")
subdirs("parcelport_mpi")
subdirs("parcelport_tcp")
subdirs("parcelset")
subdirs("parcelset_base")
subdirs("performance_counters")
subdirs("plugin_factories")
subdirs("resiliency_distributed")
subdirs("runtime_components")
subdirs("runtime_distributed")
subdirs("segmented_algorithms")
subdirs("statistics")
