# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/init_runtime_local/tests/unit
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/init_runtime_local/tests/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.unit.modules.init_runtime_local.on_finalize "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/on_finalize_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.init_runtime_local.on_finalize PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/init_runtime_local/tests/unit/CMakeLists.txt;26;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/init_runtime_local/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.init_runtime_local.shutdown_suspended_thread_local "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/shutdown_suspended_thread_local_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.init_runtime_local.shutdown_suspended_thread_local PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/init_runtime_local/tests/unit/CMakeLists.txt;26;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/init_runtime_local/tests/unit/CMakeLists.txt;0;")
