# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/full/command_line_handling/tests/regressions
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/full/command_line_handling/tests/regressions
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.regressions.modules.command_line_handling.ignore_aliases "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/ignore_aliases_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--" "-wobble=1")
set_tests_properties(tests.regressions.modules.command_line_handling.ignore_aliases PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/command_line_handling/tests/regressions/CMakeLists.txt;30;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/command_line_handling/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.command_line_handling.late_commandline_options_5257 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/late_commandline_options_5257_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.command_line_handling.late_commandline_options_5257 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/command_line_handling/tests/regressions/CMakeLists.txt;30;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/command_line_handling/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.command_line_handling.options_as_config_3339 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/options_as_config_3339_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.command_line_handling.options_as_config_3339 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/command_line_handling/tests/regressions/CMakeLists.txt;30;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/command_line_handling/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.command_line_handling.use_all_cores_2262 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/use_all_cores_2262_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.command_line_handling.use_all_cores_2262 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/command_line_handling/tests/regressions/CMakeLists.txt;30;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/command_line_handling/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.command_line_handling.configuration_1572 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/configuration_1572_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.command_line_handling.configuration_1572 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/command_line_handling/tests/regressions/CMakeLists.txt;30;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/command_line_handling/tests/regressions/CMakeLists.txt;0;")
