//  Copyright (c) 2019-2025 STE||AR Group
//
//  SPDX-License-Identifier: BSL-1.0
//  Distributed under the Boost Software License, Version 1.0. (See accompanying
//  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

// Do not edit this file! It has been generated by the cmake configuration step.

#pragma once

#include <hpx/config.hpp>

#if defined(HPX_HAVE_MODULE_SEGMENTED_ALGORITHMS)
#include <hpx/parallel/segmented_algorithm.hpp>
#include <hpx/parallel/segmented_algorithms/adjacent_difference.hpp>
#include <hpx/parallel/segmented_algorithms/adjacent_find.hpp>
#include <hpx/parallel/segmented_algorithms/all_any_none.hpp>
#include <hpx/parallel/segmented_algorithms/count.hpp>
#include <hpx/parallel/segmented_algorithms/exclusive_scan.hpp>
#include <hpx/parallel/segmented_algorithms/fill.hpp>
#include <hpx/parallel/segmented_algorithms/find.hpp>
#include <hpx/parallel/segmented_algorithms/functional/segmented_iterator_helpers.hpp>
#include <hpx/parallel/segmented_algorithms/for_each.hpp>
#include <hpx/parallel/segmented_algorithms/generate.hpp>
#include <hpx/parallel/segmented_algorithms/inclusive_scan.hpp>
#include <hpx/parallel/segmented_algorithms/minmax.hpp>
#include <hpx/parallel/segmented_algorithms/reduce.hpp>
#include <hpx/parallel/segmented_algorithms/traits/zip_iterator.hpp>
#include <hpx/parallel/segmented_algorithms/transform_exclusive_scan.hpp>
#include <hpx/parallel/segmented_algorithms/transform.hpp>
#include <hpx/parallel/segmented_algorithms/transform_inclusive_scan.hpp>
#include <hpx/parallel/segmented_algorithms/transform_reduce.hpp>
#endif

