//  Copyright (c) 2019-2025 STE||AR Group
//
//  SPDX-License-Identifier: BSL-1.0
//  Distributed under the Boost Software License, Version 1.0. (See accompanying
//  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

// Do not edit this file! It has been generated by the cmake configuration step.

#pragma once

#include <hpx/config.hpp>

#if defined(HPX_HAVE_MODULE_COROUTINES)
#include <hpx/coroutines/coroutine.hpp>
#include <hpx/coroutines/coroutine_fwd.hpp>
#include <hpx/coroutines/stackless_coroutine.hpp>
#include <hpx/coroutines/signal_handler_debugging.hpp>
#include <hpx/coroutines/thread_enums.hpp>
#include <hpx/coroutines/thread_id_type.hpp>
#endif

