# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/async_combinators/tests/regressions
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/async_combinators/tests/regressions
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.regressions.modules.async_combinators.split_future_2246 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/split_future_2246_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.async_combinators.split_future_2246 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/async_combinators/tests/regressions/CMakeLists.txt;23;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/async_combinators/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.async_combinators.when_all_vectors_1623 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/when_all_vectors_1623_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.async_combinators.when_all_vectors_1623 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/async_combinators/tests/regressions/CMakeLists.txt;23;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/async_combinators/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.async_combinators.wait_all_std_array_2035 "/opt/homebrew/bin/cmake" "--build" "/Users/harith/Desktop/Open Source/hpx/build2" "--target" "tests_regressions_modules_async_combinators_wait_all_std_array_2035" "--config" "Release")
set_tests_properties(tests.regressions.modules.async_combinators.wait_all_std_array_2035 PROPERTIES  RUN_SERIAL "TRUE" WORKING_DIRECTORY "/Users/harith/Desktop/Open Source/hpx/build2" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;48;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;74;add_hpx_compile_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;86;add_test_and_deps_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/core/async_combinators/tests/regressions/CMakeLists.txt;36;add_hpx_regression_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/core/async_combinators/tests/regressions/CMakeLists.txt;0;")
