# Copyright (c) 2021 ETH Zurich
#
# SPDX-License-Identifier: BSL-1.0
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

status = [ "Bors" ]
required_approvals = 0
delete_merged_branches = true
use_squash_merge = false

[committer]
name = "StellarBot"
email = "contact@stellar-group.org"
