#!/bin/bash
#
# Copyright (c) 2007-2008 Richard Guildry
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying 
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

rm -rf CMakeFiles/
rm -f cmake_install.cmake
rm -f CMakeCache.txt
rm -rf src/CMakeFiles/
rm -f src/cmake_install.cmake

