#!/bin/sh
#
# Copyright (c) 2007-2008 Richard Guildry
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying 
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

gcc -v 2>&1| perl -n -e 'print "$1$2\n" if(/version +(\d+)\.(\d+)/);'

