//  Copyright (c) 2019-2025 STE||AR Group
//
//  SPDX-License-Identifier: BSL-1.0
//  Distributed under the Boost Software License, Version 1.0. (See accompanying
//  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

// Do not edit this file! It has been generated by the cmake configuration step.

#pragma once

#include <hpx/config.hpp>

#if defined(HPX_HAVE_MODULE_SYNCHRONIZATION)
#include <hpx/synchronization/async_rw_mutex.hpp>
#include <hpx/synchronization/barrier.hpp>
#include <hpx/synchronization/binary_semaphore.hpp>
#include <hpx/synchronization/channel_mpmc.hpp>
#include <hpx/synchronization/channel_mpsc.hpp>
#include <hpx/synchronization/channel_spsc.hpp>
#include <hpx/synchronization/condition_variable.hpp>
#include <hpx/synchronization/counting_semaphore.hpp>
#include <hpx/synchronization/event.hpp>
#include <hpx/synchronization/latch.hpp>
#include <hpx/synchronization/lock_types.hpp>
#include <hpx/synchronization/mutex.hpp>
#include <hpx/synchronization/no_mutex.hpp>
#include <hpx/synchronization/once.hpp>
#include <hpx/synchronization/recursive_mutex.hpp>
#include <hpx/synchronization/shared_mutex.hpp>
#include <hpx/synchronization/sliding_semaphore.hpp>
#include <hpx/synchronization/spinlock.hpp>
#include <hpx/synchronization/spinlock_pool.hpp>
#include <hpx/synchronization/stop_token.hpp>
#endif

