# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/full/lcos_distributed/tests/unit
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/full/lcos_distributed/tests/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.unit.modules.lcos_distributed.channel "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/channel_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.lcos_distributed.channel PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/lcos_distributed/tests/unit/CMakeLists.txt;38;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/lcos_distributed/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.lcos_distributed.client_then "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/client_then_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.lcos_distributed.client_then PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/lcos_distributed/tests/unit/CMakeLists.txt;38;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/lcos_distributed/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.lcos_distributed.future_wait "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/future_wait_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.lcos_distributed.future_wait PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/lcos_distributed/tests/unit/CMakeLists.txt;38;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/lcos_distributed/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.lcos_distributed.packaged_action "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/packaged_action_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.lcos_distributed.packaged_action PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/lcos_distributed/tests/unit/CMakeLists.txt;38;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/lcos_distributed/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.lcos_distributed.promise "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/promise_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.lcos_distributed.promise PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/lcos_distributed/tests/unit/CMakeLists.txt;38;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/lcos_distributed/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.lcos_distributed.promise_allocator "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/promise_allocator_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.lcos_distributed.promise_allocator PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/lcos_distributed/tests/unit/CMakeLists.txt;38;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/lcos_distributed/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.lcos_distributed.promise_emplace "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/promise_emplace_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.lcos_distributed.promise_emplace PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/lcos_distributed/tests/unit/CMakeLists.txt;38;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/lcos_distributed/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.lcos_distributed.use_allocator "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/use_allocator_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.lcos_distributed.use_allocator PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/lcos_distributed/tests/unit/CMakeLists.txt;38;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/lcos_distributed/tests/unit/CMakeLists.txt;0;")
