# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/synchronization/tests/regressions
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/synchronization/tests/regressions
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.regressions.modules.synchronization.ignore_while_locked_1485 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/ignore_while_locked_1485_test" "-e" "0" "-t" "2" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.synchronization.ignore_while_locked_1485 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/synchronization/tests/regressions/CMakeLists.txt;29;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/synchronization/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.synchronization.shared_mutex_1702 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/shared_mutex_1702_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.synchronization.shared_mutex_1702 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/synchronization/tests/regressions/CMakeLists.txt;29;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/synchronization/tests/regressions/CMakeLists.txt;0;")
