#  Copyright (c) 2018 Thomas Heller
#
#  Distributed under the Boost Software License, Version 1.0. (See accompanying
#  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

.core:
    image: stellargroup/build_env:ubuntu
    stage: build
    script:
      - cd build
      - ninja core
    except:
        - gh-pages
    artifacts:
        paths:
            - build

