#  Copyright (c) 2018 Thomas Heller
#
#  Distributed under the Boost Software License, Version 1.0. (See accompanying
#  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

.release-x86: &release-x86
    variables:
        CMAKE_BUILD_TYPE: "Release"
        CMAKE_EXTRA_FLAGS: "-DCMAKE_CXX_CLANG_TIDY=clang-tidy"
    tags:
        - linux
        - x86
        - clang-7.0.1
        - boost-1.65.1

cmake Release x86:
    <<: *release-x86
    extends: .cmake

core Release x86:
    <<: *release-x86
    extends: .core
    dependencies:
        - checkout
        - cmake Release x86

examples Release x86:
    <<: *release-x86
    variables:
        TESTS: "examples"
    extends: .test
    dependencies:
        - checkout
        - core Release x86
        - get conv.xsl
        - get junit2html

tests.unit Release x86:
    <<: *release-x86
    variables:
        TESTS: "tests.unit"
    extends: .test
    dependencies:
        - checkout
        - core Release x86
        - get conv.xsl
        - get junit2html

tests.regressions Release x86:
    <<: *release-x86
    variables:
        TESTS: "tests.regressions"
    extends: .test
    dependencies:
        - checkout
        - core Release x86
        - get conv.xsl
        - get junit2html

tests.performance Release x86:
    <<: *release-x86
    variables:
        TESTS: "tests.performance"
    extends: .test
    dependencies:
        - checkout
        - core Release x86
        - get conv.xsl
        - get junit2html

tests.headers Release x86:
    <<: *release-x86
    variables:
        TESTS: "tests.headers"
    extends: .test
    dependencies:
        - checkout
        - core Release x86
        - get conv.xsl
