//  Copyright (c) 2019-2025 STE||AR Group
//
//  SPDX-License-Identifier: BSL-1.0
//  Distributed under the Boost Software License, Version 1.0. (See accompanying
//  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

// Do not edit this file! It has been generated by the cmake configuration step.

#pragma once

#include <hpx/config.hpp>

#if defined(HPX_HAVE_MODULE_UTIL)
#include <hpx/util/calculate_fanout.hpp>
#include <hpx/util/get_and_reset_value.hpp>
#include <hpx/util/get_entry_as.hpp>
#include <hpx/util/insert_checked.hpp>
#include <hpx/util/ios_flags_saver.hpp>
#include <hpx/util/manage_config.hpp>
#include <hpx/util/max.hpp>
#include <hpx/util/min.hpp>
#include <hpx/util/regex_from_pattern.hpp>
#include <hpx/util/sed_transform.hpp>
#endif

