#!groovy

// Copyright (c) 2020 ETH Zurich
//
// SPDX-License-Identifier: BSL-1.0
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

pipeline {
    agent {
        node {
            label 'ssl_daintvm1'
        }
    }
    options {
        buildDiscarder(
            logRotator(
                daysToKeepStr: "14",
                numToKeepStr: "50",
                artifactDaysToKeepStr: "14",
                artifactNumToKeepStr: "50"
            )
        )
    }
    environment {
        SPACK_ROOT = '/apps/daint/SSL/HPX/spack'
        GITHUB_TOKEN = credentials('STELLARBOT_GITHUB_TOKEN')
    }
    stages {
        stage('checkout') {
            steps {
                dir('hpx') {
                    sh '''
                    #!/bin/bash -l
                    rm -rf *
                    '''
                    checkout scm
                    echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
                } // dir
            } // steps
        }
        stage('perftests') {
            matrix {
                axes {
                    axis {
                        name 'configuration_name'
                        values 'perftests'
                    }
                }
                stages {
                    stage('perftests run') {
                        steps {
                            dir('hpx') {
                                // This stage is skipped without the catchError
                                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                    sh '''
                                    #!/bin/bash -l
                                    .jenkins/cscs-perftests/entry.sh
                                    '''
                                }
                            }
                        }
                    }
                    stage('publish report (failure)') {
                        steps {
                            dir('hpx') {
                                sh '''
                                #!/bin/bash -l
                                .jenkins/cscs-perftests/comment_github.sh
                                '''
                            } // dir
                        } // steps
                    } // stage publish report
                } // stages
            } // matrix
        } // stage perftests
    }

    post {
        always {
            archiveArtifacts artifacts: 'hpx/jenkins-hpx-*', fingerprint: true
            archiveArtifacts artifacts: 'hpx/*-Testing/**', fingerprint: true
            archiveArtifacts artifacts: 'hpx/*-reports/**', fingerprint: true
        }
    }
}
