# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replay
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/resiliency/tests/performance/replay
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.performance.modules.resiliency.replay.1d_stencil "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/1d_stencil_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.performance.modules.resiliency.replay.1d_stencil PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;286;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replay/CMakeLists.txt;37;add_hpx_performance_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replay/CMakeLists.txt;0;")
add_test(tests.performance.modules.resiliency.replay.async_replay "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_replay_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.performance.modules.resiliency.replay.async_replay PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;286;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replay/CMakeLists.txt;37;add_hpx_performance_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replay/CMakeLists.txt;0;")
add_test(tests.performance.modules.resiliency.replay.async_replay_validate "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_replay_validate_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.performance.modules.resiliency.replay.async_replay_validate PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;286;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replay/CMakeLists.txt;37;add_hpx_performance_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replay/CMakeLists.txt;0;")
add_test(tests.performance.modules.resiliency.replay.pure_async_for_replay "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/pure_async_for_replay_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.performance.modules.resiliency.replay.pure_async_for_replay PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;286;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replay/CMakeLists.txt;37;add_hpx_performance_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replay/CMakeLists.txt;0;")
add_test(tests.performance.modules.resiliency.replay.pure_dataflow "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/pure_dataflow_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.performance.modules.resiliency.replay.pure_dataflow PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;286;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replay/CMakeLists.txt;37;add_hpx_performance_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replay/CMakeLists.txt;0;")
add_test(tests.performance.modules.resiliency.replay.1d_stencil_checksum "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/1d_stencil_checksum_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.performance.modules.resiliency.replay.1d_stencil_checksum PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;286;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replay/CMakeLists.txt;37;add_hpx_performance_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replay/CMakeLists.txt;0;")
add_test(tests.performance.modules.resiliency.replay.1d_stencil_replay "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/1d_stencil_replay_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.performance.modules.resiliency.replay.1d_stencil_replay PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;286;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replay/CMakeLists.txt;37;add_hpx_performance_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replay/CMakeLists.txt;0;")
add_test(tests.performance.modules.resiliency.replay.dataflow_replay "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/dataflow_replay_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.performance.modules.resiliency.replay.dataflow_replay PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;286;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replay/CMakeLists.txt;37;add_hpx_performance_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replay/CMakeLists.txt;0;")
add_test(tests.performance.modules.resiliency.replay.dataflow_replay_validate "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/dataflow_replay_validate_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.performance.modules.resiliency.replay.dataflow_replay_validate PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;286;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replay/CMakeLists.txt;37;add_hpx_performance_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/performance/replay/CMakeLists.txt;0;")
