# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/algorithms/util
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/algorithms/tests/unit/algorithms/util
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.unit.modules.algorithms.util.test_low_level "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/test_low_level_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.algorithms.util.test_low_level PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/algorithms/util/CMakeLists.txt;27;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/algorithms/util/CMakeLists.txt;0;")
add_test(tests.unit.modules.algorithms.util.test_merge_four "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/test_merge_four_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.algorithms.util.test_merge_four PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/algorithms/util/CMakeLists.txt;27;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/algorithms/util/CMakeLists.txt;0;")
add_test(tests.unit.modules.algorithms.util.test_merge_vector "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/test_merge_vector_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.algorithms.util.test_merge_vector PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/algorithms/util/CMakeLists.txt;27;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/algorithms/util/CMakeLists.txt;0;")
add_test(tests.unit.modules.algorithms.util.test_nbits "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/test_nbits_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.algorithms.util.test_nbits PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/algorithms/util/CMakeLists.txt;27;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/algorithms/util/CMakeLists.txt;0;")
add_test(tests.unit.modules.algorithms.util.test_range "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/test_range_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.algorithms.util.test_range PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/algorithms/util/CMakeLists.txt;27;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/algorithms/util/CMakeLists.txt;0;")
add_test(tests.unit.modules.algorithms.util.test_simd_helpers "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/test_simd_helpers_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.algorithms.util.test_simd_helpers PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/algorithms/util/CMakeLists.txt;27;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/algorithms/util/CMakeLists.txt;0;")
