//  Copyright (c) 2019-2025 STE||AR Group
//
//  SPDX-License-Identifier: BSL-1.0
//  Distributed under the Boost Software License, Version 1.0. (See accompanying
//  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

// Do not edit this file! It has been generated by the cmake configuration step.

#pragma once

#include <hpx/config.hpp>

#if defined(HPX_HAVE_MODULE_ASYNC_COMBINATORS)
#include <hpx/async_combinators/split_future.hpp>
#include <hpx/async_combinators/wait_all.hpp>
#include <hpx/async_combinators/wait_any.hpp>
#include <hpx/async_combinators/wait_each.hpp>
#include <hpx/async_combinators/wait_some.hpp>
#include <hpx/async_combinators/when_all.hpp>
#include <hpx/async_combinators/when_any.hpp>
#include <hpx/async_combinators/when_each.hpp>
#include <hpx/async_combinators/when_some.hpp>
#endif

