# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/synchronization/tests/unit/shared_mutex
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/synchronization/tests/unit/shared_mutex
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.unit.modules.synchronization.shared_mutex.shared_mutex1 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/shared_mutex1_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.synchronization.shared_mutex.shared_mutex1 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/synchronization/tests/unit/shared_mutex/CMakeLists.txt;28;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/synchronization/tests/unit/shared_mutex/CMakeLists.txt;0;")
add_test(tests.unit.modules.synchronization.shared_mutex.shared_mutex2 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/shared_mutex2_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.synchronization.shared_mutex.shared_mutex2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/synchronization/tests/unit/shared_mutex/CMakeLists.txt;28;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/synchronization/tests/unit/shared_mutex/CMakeLists.txt;0;")
