//  Copyright (c) 2019-2025 STE||AR Group
//
//  SPDX-License-Identifier: BSL-1.0
//  Distributed under the Boost Software License, Version 1.0.
//  (See accompanying file LICENSE_1_0.txt or copy at
//  http://www.boost.org/LICENSE_1_0.txt)

// Do not edit this file! It has been generated by the CMake configuration step.

#pragma once

#include <hpx/config/attributes.hpp>
#include <hpx/config/auto_vectorization.hpp>
#include <hpx/config/branch_hints.hpp>
#include <hpx/config/compiler_fence.hpp>
#include <hpx/config/compiler_specific.hpp>
#include <hpx/config/constexpr.hpp>
#include <hpx/config/debug.hpp>
#include <hpx/config/deprecation.hpp>
#include <hpx/config/emulate_deleted.hpp>
#include <hpx/config/export_definitions.hpp>
#include <hpx/config/forceinline.hpp>
#include <hpx/config/forward.hpp>
#include <hpx/config/lambda_capture_this.hpp>
#include <hpx/config/manual_profiling.hpp>
#include <hpx/config/move.hpp>
#include <hpx/config/threads_stack.hpp>
#include <hpx/config/weak_symbol.hpp>
