# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/type_support/tests/unit
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/type_support/tests/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.unit.modules.type_support.relocate "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/relocate_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.type_support.relocate PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/type_support/tests/unit/CMakeLists.txt;29;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/type_support/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.type_support.relocate_at "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/relocate_at_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.type_support.relocate_at PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/type_support/tests/unit/CMakeLists.txt;29;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/type_support/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.type_support.uninitialized_relocate_n_primitive "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/uninitialized_relocate_n_primitive_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.type_support.uninitialized_relocate_n_primitive PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/type_support/tests/unit/CMakeLists.txt;29;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/type_support/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.type_support.is_relocatable "/opt/homebrew/bin/cmake" "--build" "/Users/harith/Desktop/Open Source/hpx/build2" "--target" "tests_unit_modules_type_support_is_relocatable" "--config" "Release")
set_tests_properties(tests.unit.modules.type_support.is_relocatable PROPERTIES  RUN_SERIAL "TRUE" WORKING_DIRECTORY "/Users/harith/Desktop/Open Source/hpx/build2" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;48;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;74;add_hpx_compile_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;82;add_test_and_deps_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/core/type_support/tests/unit/CMakeLists.txt;53;add_hpx_unit_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/core/type_support/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.type_support.is_trivially_relocatable "/opt/homebrew/bin/cmake" "--build" "/Users/harith/Desktop/Open Source/hpx/build2" "--target" "tests_unit_modules_type_support_is_trivially_relocatable" "--config" "Release")
set_tests_properties(tests.unit.modules.type_support.is_trivially_relocatable PROPERTIES  RUN_SERIAL "TRUE" WORKING_DIRECTORY "/Users/harith/Desktop/Open Source/hpx/build2" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;48;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;74;add_hpx_compile_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;82;add_test_and_deps_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/core/type_support/tests/unit/CMakeLists.txt;53;add_hpx_unit_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/core/type_support/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.type_support.is_contiguous_iterator "/opt/homebrew/bin/cmake" "--build" "/Users/harith/Desktop/Open Source/hpx/build2" "--target" "tests_unit_modules_type_support_is_contiguous_iterator" "--config" "Release")
set_tests_properties(tests.unit.modules.type_support.is_contiguous_iterator PROPERTIES  RUN_SERIAL "TRUE" WORKING_DIRECTORY "/Users/harith/Desktop/Open Source/hpx/build2" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;48;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;74;add_hpx_compile_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;82;add_test_and_deps_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/core/type_support/tests/unit/CMakeLists.txt;53;add_hpx_unit_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/core/type_support/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.type_support.fail_relocate_at "/opt/homebrew/bin/cmake" "--build" "/Users/harith/Desktop/Open Source/hpx/build2" "--target" "tests_unit_modules_type_support_fail_relocate_at" "--config" "Release")
set_tests_properties(tests.unit.modules.type_support.fail_relocate_at PROPERTIES  RUN_SERIAL "TRUE" WILL_FAIL "TRUE" WORKING_DIRECTORY "/Users/harith/Desktop/Open Source/hpx/build2" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;48;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;74;add_hpx_compile_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;82;add_test_and_deps_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/core/type_support/tests/unit/CMakeLists.txt;53;add_hpx_unit_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/core/type_support/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.type_support.fail_uninitialized_relocate "/opt/homebrew/bin/cmake" "--build" "/Users/harith/Desktop/Open Source/hpx/build2" "--target" "tests_unit_modules_type_support_fail_uninitialized_relocate" "--config" "Release")
set_tests_properties(tests.unit.modules.type_support.fail_uninitialized_relocate PROPERTIES  RUN_SERIAL "TRUE" WILL_FAIL "TRUE" WORKING_DIRECTORY "/Users/harith/Desktop/Open Source/hpx/build2" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;48;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;74;add_hpx_compile_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;82;add_test_and_deps_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/core/type_support/tests/unit/CMakeLists.txt;53;add_hpx_unit_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/core/type_support/tests/unit/CMakeLists.txt;0;")
