# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/regressions
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/iterator_support/tests/regressions
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.regressions.modules.iterator_support.custom_iterator_category_6640 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/custom_iterator_category_6640_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.iterator_support.custom_iterator_category_6640 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/regressions/CMakeLists.txt;27;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.iterator_support.zip_iterator_different_range_length "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/zip_iterator_different_range_length_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.iterator_support.zip_iterator_different_range_length PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/regressions/CMakeLists.txt;27;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/regressions/CMakeLists.txt;0;")
