#  Copyright (c) 2017-2018 Thomas Heller
#  Copyright (c) 2015 Martin Stumpf
#
#  SPDX-License-Identifier: BSL-1.0
#  Distributed under the Boost Software License, Version 1.0. (See accompanying
#  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

working_dir_default: &working_dir_default
    working_directory: /hpx/build

docker_default: &docker_default
    docker:
      - image: stellargroup/build_env:7

defaults: &defaults
    <<: *working_dir_default
    <<: *docker_default

convert_xml: &convert_xml
    name: Converting XML
    when: always
    command: |
        mkdir -p ${CIRCLE_JOB}
        xsltproc \
          /hpx/conv.xsl Testing/`head -n 1 < Testing/TAG`/Test.xml \
          > ${CIRCLE_JOB}/Test.xml

move_core_dump: &move_core_dump
    name: Moving core dumps
    when: on_fail
    command: |
        mkdir -p ${CIRCLE_JOB}
        # Ignore errors if there are no core dumps
        cp core.* ${CIRCLE_JOB} || true

move_debug_log: &move_debug_log
    name: Moving debug logs
    when: on_fail
    command: |
        mkdir -p ${CIRCLE_JOB}
        cp debug-log.txt ${CIRCLE_JOB} || true

core_dependency: &core_dependency
    requires:
      - core

add_github_to_known_hosts: &add_github_to_known_hosts
    run:
        name: Add Github's key(s) to known_hosts
        command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H github.com >>~/.ssh/known_hosts
configure_local_git: &configure_local_git
    run:
        name: Configure local Git
        command: |
            git config --global user.name "StellarBot"
            git config --global user.email "stellar@cct.lsu.edu"


version: 2

jobs:
  checkout_code:
    <<: *docker_default
    working_directory: /hpx
    steps:
      - checkout:
          path: /hpx/source-full
      # Make a shallow clone of the current commit so that we don't have to copy
      # the whole repository between work steps.
      - run:
          name: Creating shallow clone
          command: |
              git clone --depth=1 file:///hpx/source-full source
      - run:
          name: Downloading CTest XML to Junit XML
          command: |
              curl \
                https://raw.githubusercontent.com/Kitware/CDash/master/app/cdash/tests/circle/conv.xsl \
                --fail \
                -o /hpx/conv.xsl
      - persist_to_workspace:
          root: /hpx
          paths:
            - ./source
            - ./conv.xsl

  # Check circular dependencies with cpp-dependencies tool
  check_circular_deps:
    <<: *working_dir_default
    <<: *docker_default
    steps:
      - attach_workspace:
          at: /hpx
      - run:
          name: Check circular dependencies with cpp-dependencies
          command: |
              # Ignore compatibility headers (the last cut -c3- is to remove a
              # leading ./ in path names)
              cpp-dependencies \
                  --dir /hpx/source/libs \
                  --ignore $(find /hpx/source/libs -type d -wholename '*/include_compatibility' | cut -d'/' -f5-) \
                  --graph-cycles /tmp/circular_deps.dot
              dot /tmp/circular_deps.dot -Tsvg -o /tmp/circular_deps.svg
              if [[ $(wc -l /tmp/circular_deps.dot | awk '{print $1}') -gt 2 ]]; then exit 1; fi
      - store_artifacts:
          path: /tmp/circular_deps.dot
          destination: /hpx/artifacts/circular_deps.dot
      - store_artifacts:
          path: /tmp/circular_deps.svg
          destination: /hpx/artifacts/circular_deps.svg

  # Check if the files of the module are listed in the CMakeLists.txt
  # Check if all the module dependencies are listed
  check_module_cmakelists:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /hpx
      - run:
          name: Check if the headers of the modules are listed in their CMakeLists.txt
          command: |
              /hpx/source/tools/check_module_cmakelists.sh
              if [[ $(wc -l /tmp/missing_files.txt | awk '{print $1}') -gt 1 ]] \
                  || [[ $(wc -l /tmp/missing_deps.txt | awk '{print $1}') -gt 1 ]]; \
                  then exit 1; fi
      - store_artifacts:
          path: /tmp/missing_files.txt
          destination: /hpx/artifacts/missing_files.txt
      - store_artifacts:
          path: /tmp/missing_deps.txt
          destination: /hpx/artifacts/missing_deps.txt

  # Ensure that the modules stay clang-formatted
  clang_format:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /hpx
      - run:
          name: Check that the modules are well clang-formatted
          command: |
              cd /hpx/source/libs && shopt -s globstar # to activate the ** globbing
              clang-format-11 --version
              clang-format-11 -i **/*.{cpp,hpp}
              git diff --exit-code > /tmp/modified_clang_format_files.txt
      - store_artifacts:
          path: /tmp/modified_clang_format_files.txt
          destination: /hpx/artifacts/modified_clang_format_files.txt

  # Ensure that CMake files stay cmake-formatted
  cmake_format:
    <<: *docker_default
    steps:
      - attach_workspace:
          at: /hpx
      - run:
          name: Check that CMake files are well cmake-formatted
          command: |
              cd /hpx/source && shopt -s globstar # to activate the ** globbing
              cmake-format --version
              cmake-format -i **/*.cmake **/CMakeLists.txt
              git diff --exit-code > /tmp/modified_cmake_format_files.txt
      - store_artifacts:
          path: /tmp/modified_cmake_format_files.txt
          destination: /hpx/artifacts/modified_cmake_format_files.txt

  configure:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /hpx
      - run:
          name: Running CMake
          command: |
            cmake --version
            cmake \
                /hpx/source \
                -G "Ninja" \
                -DCMAKE_BUILD_TYPE=Debug \
                -DCMAKE_CXX_CLANG_TIDY=clang-tidy \
                -DCMAKE_CXX_FLAGS="-fcolor-diagnostics" \
                -DHPXLocal_WITH_GIT_COMMIT=${CIRCLE_SHA1} \
                -DHPXLocal_WITH_GIT_BRANCH="${CIRCLE_BRANCH}" \
                -DHPXLocal_WITH_GIT_TAG="${CIRCLE_TAG}" \
                -DHPXLocal_WITH_FETCH_ASIO=On \
                -DHPXLocal_WITH_TOOLS=On \
                -DHPXLocal_WITH_MALLOC=system \
                -DHPXLocal_WITH_EXAMPLES=On \
                -DHPXLocal_WITH_TESTS=On \
                -DHPXLocal_WITH_TESTS_HEADERS=On \
                -DHPXLocal_WITH_DATAPAR_VC=On \
                -DHPXLocal_WITH_COMPILER_WARNINGS=On \
                -DHPXLocal_WITH_COMPILER_WARNINGS_AS_ERRORS=On \
                -DHPXLocal_WITH_DEPRECATION_WARNINGS=On \
                -DHPXLocal_WITH_THREAD_LOCAL_STORAGE=On \
                -DHPXLocal_WITH_STACKTRACES_STATIC_SYMBOLS=On \
                -DHPXLocal_WITH_STACKTRACES_DEMANGLE_SYMBOLS=Off \
                -DHPXLocal_WITH_TESTS_DEBUG_LOG=On \
                -DHPXLocal_WITH_TESTS_DEBUG_LOG_DESTINATION=/hpx/build/debug-log.txt \
                -DHPXLocal_WITH_SPINLOCK_DEADLOCK_DETECTION=On \
                -DHPXLocal_WITH_CHECK_MODULE_DEPENDENCIES=On \
                -DCMAKE_EXPORT_COMPILE_COMMANDS=On
      - persist_to_workspace:
          root: /hpx
          paths:
            - ./build

  configure_test_combinations:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /hpx
      - run:
          name: Running CMake with tests on and examples off
          command: |
            cmake \
                /hpx/source \
                -G "Ninja" \
                -DHPXLocal_WITH_MALLOC=system \
                -DHPXLocal_WITH_FETCH_ASIO=On \
                -DHPXLocal_WITH_TESTS=On \
                -DHPXLocal_WITH_EXAMPLES=Off
            rm -rf *
      - run:
          name: Running CMake with tests off and examples on
          command: |
            cmake \
                /hpx/source \
                -G "Ninja" \
                -DHPXLocal_WITH_MALLOC=system \
                -DHPXLocal_WITH_FETCH_ASIO=On \
                -DHPXLocal_WITH_TESTS=Off \
                -DHPXLocal_WITH_EXAMPLES=On
            rm -rf *
      - run:
          name: Running CMake with APEX on
          command: |
            cmake \
                /hpx/source \
                -G "Ninja" \
                -DHPXLocal_WITH_MALLOC=system \
                -DHPXLocal_WITH_FETCH_ASIO=On \
                -DHPXLocal_WITH_APEX=On \
                -DHPXLocal_WITH_TESTS=On \
                -DHPXLocal_WITH_EXAMPLES=On
            rm -rf *
      - persist_to_workspace:
          root: /hpx
          paths:
            - ./build

  inspect:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /hpx
      - run:
          name: Building Inspect Tool
          command: |
              ninja -j2 tools.inspect
      - run:
          name: Running Inspect Tool
          command: |
              ./bin/inspect --all --output=./hpx_inspect_report.html /hpx/source
      - run:
          name: Convert inspect HTML output to XML
          command: |
              mkdir -p /report
              /hpx/source/tools/inspect/inspect_to_junit.py \
                  ./hpx_inspect_report.html \
                  /report/hpx_inspect.xml
          when: always
      - store_artifacts:
          path: hpx_inspect_report.html
          destination: hpx_inspect_report.html
      - store_test_results:
          path: /report
      - persist_to_workspace:
          root: /hpx
          paths:
            - ./build/bin/inspect

  # We need a full clone here to be able to compare to master.
  spellcheck:
    <<: *defaults
    steps:
      - checkout:
          path: /hpx/source
      - run:
          name: Running codespell
          command: |
              if [[ -n "$CIRCLE_PULL_REQUEST" ]]; then
                  cd /hpx/source
                  codespell --version
                  codespell --ignore-words tools/.codespell_whitelist --skip='*.h5,*.png' $(git diff --name-only origin/master...) > /tmp/spelling_suggestions.txt
                  if [ -s /tmp/spelling_suggestions.txt ]; then exit 1; fi
              else
                  echo "skipping spellcheck on non-PR build"
              fi
          when: always
      - store_artifacts:
          path: /tmp/spelling_suggestions.txt
          destination: /hpx/artifacts/spelling_suggestions.txt

  core:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /hpx
      - run:
          name: Building Core
          command: |
              ninja -j2 -k 0 hpx_local
      - persist_to_workspace:
          root: /hpx
          paths:
            - ./build

  tests.examples:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /hpx
      - run:
          name: Building Examples
          command: |
              ninja -j2 -k 0 examples
      - run:
          name: Running Example Tests
          when: always
          command: |
              ulimit -c unlimited
              # NOTE: transpose_block_numa is disabled because
              # hwloc_get_area_membind_nodeset (which is used by the
              # numa_allocator) fails with EPERM.
              ctest --timeout 60 -T test --no-compress-output --output-on-failure \
                  -R tests.examples \
                  -E tests.examples.transpose.transpose_block_numa
      - run:
          <<: *convert_xml
      - run:
          <<: *move_core_dump
      - run:
          <<: *move_debug_log
      - store_test_results:
          path: tests.examples
      - store_artifacts:
          path: tests.examples
      - persist_to_workspace:
          root: /hpx
          paths:
            - ./build

  tests.unit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /hpx
      - run:
          name: Building Unit Tests
          command: |
              ninja -j2 -k 0 tests.unit
      - run:
          name: Running Unit Tests
          when: always
          command: |
              ulimit -c unlimited
              ctest \
                --timeout 120 \
                -T test \
                --no-compress-output \
                --output-on-failure \
                --tests-regex tests.unit \
                --exclude-regex \
              "tests.unit.modules.compute.numa_allocator|\
              tests.unit.modules.resource_partitioner.scheduler_binding_check"
      - run:
          <<: *convert_xml
      - run:
          <<: *move_core_dump
      - run:
          <<: *move_debug_log
      - store_test_results:
          path: tests.unit
      - store_artifacts:
          path: tests.unit

      - run:
          <<: *convert_xml
      - run:
          <<: *move_core_dump
      - run:
          <<: *move_debug_log
      - store_test_results:
          path: tests.unit2
      - store_artifacts:
          path: tests.unit2

  tests.regressions:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /hpx
      - run:
          name: Building Regressions Tests
          command: |
              ninja -j2 -k 0 tests.regressions
      - run:
          name: Running Regressions Tests
          when: always
          command: |
              ctest --timeout 60 -T test --no-compress-output --output-on-failure -R tests.regressions
      - run:
          <<: *convert_xml
      - run:
          <<: *move_core_dump
      - run:
          <<: *move_debug_log
      - store_test_results:
          path: tests.regressions
      - store_artifacts:
          path: tests.regressions

  tests.headers:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /hpx
      - run:
          name: Building Header Tests
          command: |
              ctest --timeout 60 -j1 -T test --no-compress-output --output-on-failure -R tests.headers
      - run:
          <<: *convert_xml
      - store_test_results:
          path: tests.headers
      - store_artifacts:
          path: tests.headers

  tests.performance:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /hpx
      - run:
          name: Building Performance Tests
          command: |
              ninja -j2 -k 0 tests.performance

  install:
    <<: *docker_default
    environment:
      TARGET_IMAGE_NAME: stellargroup/hpx:dev
    steps:
      - attach_workspace:
          at: /hpx
      - setup_remote_docker
      - run:
          name: Installing
          command: |
              ./bin/hello_world --hpx:bind=none
              # Disable Vc here as the target machine of the container image may
              # not support the same vector intrinsics as this machine. The
              # "Test Docker Image" below fails with "Illegal instruction" if VC
              # is enabled, and other machines may fail similarly.
              cmake -DHPXLocal_WITH_DATAPAR_VC=Off .
              ninja -j2 install
          working_directory: /hpx/build
          when: always
          no_output_timeout: 30m
      - run:
          name: Testing build unit tests
          command: |
              ninja -j2 tests.unit.build
          working_directory: /hpx/build
          when: always
      - run:
          name: Testing installed HPX
          command: |
              hello_world --hpx:bind=none
          working_directory: /hpx/build
          when: always
      - run:
          name: Create Docker Image
          command: |
              cp /hpx/source/tools/docker/Dockerfile .
              VER="18.03.0-ce"
              curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
              tar -xz -C /tmp -f /tmp/docker-$VER.tgz
              mv /tmp/docker/* /usr/bin
              docker build -t ${TARGET_IMAGE_NAME} .
          working_directory: /usr/local
      - run:
          name: Test Docker Image
          command: |
              docker run ${TARGET_IMAGE_NAME} hello_world --hpx:bind=none
          working_directory: /hpx

  # This is the final step once everything else passes. We need a full clone
  # here again to be able to push the new tag.
  push_stable_tag:
    <<: *docker_default
    steps:
      - checkout:
          path: /hpx/source
      - <<: *add_github_to_known_hosts
      - <<: *configure_local_git
      - run:
          name: Push stable tag
          command: |
              if [[ -z "$CIRCLE_PR_NUMBER" ]] && [[ "$CIRCLE_BRANCH" == "master" ]]; then
                  # Tag the commit
                  cd /hpx/source
                  git tag -f stable
                  ##########################################################
                  # NOTE: Dependency on the Docker push is so that users who
                  # use the Docker image would not be confused. Do not change
                  # the order before considering every use case.
                  ##########################################################
                  # Remove the old tag
                  git push origin :refs/tags/stable
                  # Push the new stable commit tag
                  git push origin stable
              else
                  echo "Not on the master branch. The commit will not be tagged."
              fi

workflows:
  version: 2
  build-and-test:
    jobs:
      - checkout_code
      - check_circular_deps:
          requires:
            - checkout_code
      - check_module_cmakelists:
          requires:
            - checkout_code
      - clang_format:
          requires:
            - checkout_code
      - cmake_format:
          requires:
            - checkout_code
      - configure:
          requires:
            - checkout_code
      - configure_test_combinations:
          requires:
            - checkout_code
      - inspect:
          requires:
            - configure
      - spellcheck
      - core:
          requires:
            - configure
      - tests.examples:
          <<: *core_dependency
      - tests.unit:
          <<: *core_dependency
      - tests.regressions:
          <<: *core_dependency
      - tests.performance:
          <<: *core_dependency
      - tests.headers:
          <<: *core_dependency
      - install:
          requires:
            - core
            - tests.examples
            - tests.unit
            - tests.regressions
            - tests.performance
            - tests.headers
      - push_stable_tag:
          requires:
            - install
