#  Copyright (c) 2017-2018 Thomas Heller
#  Copyright (c) 2015 Martin Stumpf
#
#  Distributed under the Boost Software License, Version 1.0. (See accompanying
#  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

version: 2

jobs:
  dummy:
    docker:
      - image: stellargroup/build_env:ubuntu
    steps:
      - run:
          name: Dummy
          command: |
              echo "This is a dummy"

workflows:
  version: 2
  build-and-test:
    jobs:
      - dummy:
