# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/program_options/examples
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/program_options/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.examples.modules.program_options.config_file_types "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/config_file_types" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.modules.program_options.config_file_types PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/examples/CMakeLists.txt;58;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/examples/CMakeLists.txt;0;")
add_test(tests.examples.modules.program_options.custom_syntax "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/custom_syntax" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.modules.program_options.custom_syntax PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/examples/CMakeLists.txt;58;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/examples/CMakeLists.txt;0;")
add_test(tests.examples.modules.program_options.env_options "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/env_options" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.modules.program_options.env_options PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/examples/CMakeLists.txt;58;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/examples/CMakeLists.txt;0;")
add_test(tests.examples.modules.program_options.first "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/first" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.modules.program_options.first PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/examples/CMakeLists.txt;58;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/examples/CMakeLists.txt;0;")
add_test(tests.examples.modules.program_options.multiple_sources "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/multiple_sources" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.modules.program_options.multiple_sources PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/examples/CMakeLists.txt;58;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/examples/CMakeLists.txt;0;")
add_test(tests.examples.modules.program_options.option_groups "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/option_groups" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.modules.program_options.option_groups PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/examples/CMakeLists.txt;58;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/examples/CMakeLists.txt;0;")
add_test(tests.examples.modules.program_options.options_description "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/options_description" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.modules.program_options.options_description PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/examples/CMakeLists.txt;58;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/examples/CMakeLists.txt;0;")
add_test(tests.examples.modules.program_options.options_hierarchy "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/options_hierarchy" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.modules.program_options.options_hierarchy PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/examples/CMakeLists.txt;58;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/examples/CMakeLists.txt;0;")
add_test(tests.examples.modules.program_options.real "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/real" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.modules.program_options.real PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/examples/CMakeLists.txt;58;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/examples/CMakeLists.txt;0;")
add_test(tests.examples.modules.program_options.regex "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/regex" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.modules.program_options.regex PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/examples/CMakeLists.txt;58;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/examples/CMakeLists.txt;0;")
add_test(tests.examples.modules.program_options.response_file "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/response_file" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.modules.program_options.response_file PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/examples/CMakeLists.txt;58;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/examples/CMakeLists.txt;0;")
