# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/tests/regressions/util
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/tests/regressions/util
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.regressions.util.set_config_entry_deadlock "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/set_config_entry_deadlock_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.util.set_config_entry_deadlock PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/util/CMakeLists.txt;38;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/util/CMakeLists.txt;0;")
add_test(tests.regressions.util.iarchive_1237 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/iarchive_1237_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.util.iarchive_1237 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/util/CMakeLists.txt;38;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/util/CMakeLists.txt;0;")
add_test(tests.regressions.util.serialize_buffer_1069 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/serialize_buffer_1069_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.util.serialize_buffer_1069 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/util/CMakeLists.txt;38;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/util/CMakeLists.txt;0;")
add_test(tests.regressions.util.distributed.tcp.serialize_exception_4886 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/serialize_exception_4886_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.regressions.util.distributed.tcp.serialize_exception_4886 PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/util/CMakeLists.txt;38;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/util/CMakeLists.txt;0;")
add_test(tests.regressions.util.distributed.tcp.zero_copy_parcels_1001 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/zero_copy_parcels_1001_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.regressions.util.distributed.tcp.zero_copy_parcels_1001 PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/util/CMakeLists.txt;38;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/util/CMakeLists.txt;0;")
add_test(tests.regressions.util.distributed.tcp.zero_copy_parcels_1001_no_array_optimization "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/zero_copy_parcels_1001_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--" "PSEUDO_DEPS_NAME" "zero_copy_parcels_1001")
set_tests_properties(tests.regressions.util.distributed.tcp.zero_copy_parcels_1001_no_array_optimization PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/util/CMakeLists.txt;44;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/util/CMakeLists.txt;0;")
add_test(tests.regressions.util.distributed.tcp.zero_copy_parcels_1001_no_zero_copy_optimization "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/zero_copy_parcels_1001_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--" "PSEUDO_DEPS_NAME" "zero_copy_parcels_1001")
set_tests_properties(tests.regressions.util.distributed.tcp.zero_copy_parcels_1001_no_zero_copy_optimization PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/util/CMakeLists.txt;51;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/util/CMakeLists.txt;0;")
add_test(tests.regressions.util.distributed.tcp.zero_copy_parcels_1001_no_zero_copy_receive_optimization "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/zero_copy_parcels_1001_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--" "PSEUDO_DEPS_NAME" "zero_copy_parcels_1001")
set_tests_properties(tests.regressions.util.distributed.tcp.zero_copy_parcels_1001_no_zero_copy_receive_optimization PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/util/CMakeLists.txt;58;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/util/CMakeLists.txt;0;")
