# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/unit
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/resiliency/tests/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.unit.modules.resiliency.async_replay_executor "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_replay_executor_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.resiliency.async_replay_executor PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/unit/CMakeLists.txt;41;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.resiliency.async_replay_plain "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_replay_plain_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.resiliency.async_replay_plain PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/unit/CMakeLists.txt;41;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.resiliency.async_replicate_executor "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_replicate_executor_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.resiliency.async_replicate_executor PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/unit/CMakeLists.txt;41;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.resiliency.async_replicate_plain "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_replicate_plain_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.resiliency.async_replicate_plain PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/unit/CMakeLists.txt;41;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.resiliency.async_replicate_vote_executor "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_replicate_vote_executor_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.resiliency.async_replicate_vote_executor PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/unit/CMakeLists.txt;41;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.resiliency.async_replicate_vote_plain "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_replicate_vote_plain_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.resiliency.async_replicate_vote_plain PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/unit/CMakeLists.txt;41;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.resiliency.replay_executor "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/replay_executor_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.resiliency.replay_executor PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/unit/CMakeLists.txt;41;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.resiliency.replicate_executor "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/replicate_executor_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.resiliency.replicate_executor PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/unit/CMakeLists.txt;41;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.resiliency.dataflow_replay_executor "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/dataflow_replay_executor_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.resiliency.dataflow_replay_executor PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/unit/CMakeLists.txt;41;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.resiliency.dataflow_replay_plain "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/dataflow_replay_plain_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.resiliency.dataflow_replay_plain PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/unit/CMakeLists.txt;41;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.resiliency.dataflow_replicate_executor "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/dataflow_replicate_executor_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.resiliency.dataflow_replicate_executor PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/unit/CMakeLists.txt;41;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.resiliency.dataflow_replicate_plain "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/dataflow_replicate_plain_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.resiliency.dataflow_replicate_plain PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/unit/CMakeLists.txt;41;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/tests/unit/CMakeLists.txt;0;")
