#!/usr/bin/perl -w
# Matt Anderson
# 30 Jan 2007
# Run sdf2o
use File::Copy;

$nx = 100;
$dt = 0.25 * 8.0/($nx-1);

@fields = qw(d4phi);
foreach $field (@fields) {
  for ($i=0;$i<6;$i++) {
    for ($level=0;$level<2;$level++) {
      $time = 0.0 + $i*3*$dt;
      print "sdf2o 1 $level $time $field\n";
      system("sdf2o 1 $level $time $field");

      $file = $field . "_r.sdf";
      $levelfile = $field . "_" . $level . "_" . $time . ".sdf";
      copy($file,$levelfile);
      unlink($file);
    }
  }
}

