# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/components/containers/partitioned_vector/tests/unit
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/components/containers/partitioned_vector/tests/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.unit.components.partitioned_vector.is_iterator_partitioned_vector "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/is_iterator_partitioned_vector_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.components.partitioned_vector.is_iterator_partitioned_vector PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/components/containers/partitioned_vector/tests/unit/CMakeLists.txt;61;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/components/containers/partitioned_vector/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.components.partitioned_vector.partitioned_vector_view "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/partitioned_vector_view_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.components.partitioned_vector.partitioned_vector_view PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/components/containers/partitioned_vector/tests/unit/CMakeLists.txt;61;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/components/containers/partitioned_vector/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.components.partitioned_vector.partitioned_vector_view_iterator "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/partitioned_vector_view_iterator_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.components.partitioned_vector.partitioned_vector_view_iterator PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/components/containers/partitioned_vector/tests/unit/CMakeLists.txt;61;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/components/containers/partitioned_vector/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.components.partitioned_vector.partitioned_vector_subview "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/partitioned_vector_subview_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.components.partitioned_vector.partitioned_vector_subview PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/components/containers/partitioned_vector/tests/unit/CMakeLists.txt;61;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/components/containers/partitioned_vector/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.components.partitioned_vector.coarray "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/coarray_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.components.partitioned_vector.coarray PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/components/containers/partitioned_vector/tests/unit/CMakeLists.txt;61;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/components/containers/partitioned_vector/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.components.partitioned_vector.coarray_all_reduce "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/coarray_all_reduce_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.components.partitioned_vector.coarray_all_reduce PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/components/containers/partitioned_vector/tests/unit/CMakeLists.txt;61;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/components/containers/partitioned_vector/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.components.partitioned_vector.serialization_partitioned_vector "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/serialization_partitioned_vector_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.components.partitioned_vector.serialization_partitioned_vector PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/components/containers/partitioned_vector/tests/unit/CMakeLists.txt;61;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/components/containers/partitioned_vector/tests/unit/CMakeLists.txt;0;")
