# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/full/parcelset/tests/unit
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/full/parcelset/tests/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.unit.modules.parcelset.distributed.tcp.put_parcels "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/put_parcels_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.unit.modules.parcelset.distributed.tcp.put_parcels PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/parcelset/tests/unit/CMakeLists.txt;34;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/parcelset/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.parcelset.distributed.tcp.set_parcel_write_handler "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/set_parcel_write_handler_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.unit.modules.parcelset.distributed.tcp.set_parcel_write_handler PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/parcelset/tests/unit/CMakeLists.txt;34;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/parcelset/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.parcelset.distributed.tcp.zero_copy_parcel "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/zero_copy_parcel_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.unit.modules.parcelset.distributed.tcp.zero_copy_parcel PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/parcelset/tests/unit/CMakeLists.txt;34;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/parcelset/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.parcelset.distributed.tcp.zero_copy_parcel_no_array_optimization "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/zero_copy_parcel_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--" "PSEUDO_DEPS_NAME" "zero_copy_parcel")
set_tests_properties(tests.unit.modules.parcelset.distributed.tcp.zero_copy_parcel_no_array_optimization PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/parcelset/tests/unit/CMakeLists.txt;41;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/parcelset/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.parcelset.distributed.tcp.zero_copy_parcel_no_zero_copy_optimization "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/zero_copy_parcel_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--" "PSEUDO_DEPS_NAME" "zero_copy_parcel")
set_tests_properties(tests.unit.modules.parcelset.distributed.tcp.zero_copy_parcel_no_zero_copy_optimization PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/parcelset/tests/unit/CMakeLists.txt;49;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/parcelset/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.parcelset.distributed.tcp.zero_copy_parcel_no_zero_copy_receive_optimization "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/zero_copy_parcel_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--" "PSEUDO_DEPS_NAME" "zero_copy_parcel")
set_tests_properties(tests.unit.modules.parcelset.distributed.tcp.zero_copy_parcel_no_zero_copy_receive_optimization PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/parcelset/tests/unit/CMakeLists.txt;57;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/parcelset/tests/unit/CMakeLists.txt;0;")
