# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/unit
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/iterator_support/tests/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.unit.modules.iterator_support.boost_iterator_categories "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/boost_iterator_categories_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.iterator_support.boost_iterator_categories PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/unit/CMakeLists.txt;47;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.iterator_support.counting_iterator "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/counting_iterator_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.iterator_support.counting_iterator PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/unit/CMakeLists.txt;47;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.iterator_support.is_iterator "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/is_iterator_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.iterator_support.is_iterator PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/unit/CMakeLists.txt;47;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.iterator_support.is_range "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/is_range_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.iterator_support.is_range PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/unit/CMakeLists.txt;47;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.iterator_support.iterator_adaptor "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/iterator_adaptor_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.iterator_support.iterator_adaptor PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/unit/CMakeLists.txt;47;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.iterator_support.iterator_facade "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/iterator_facade_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.iterator_support.iterator_facade PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/unit/CMakeLists.txt;47;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.iterator_support.range "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/range_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.iterator_support.range PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/unit/CMakeLists.txt;47;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.iterator_support.stencil3_iterator "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/stencil3_iterator_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.iterator_support.stencil3_iterator PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/unit/CMakeLists.txt;47;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.iterator_support.transform_iterator "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/transform_iterator_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.iterator_support.transform_iterator PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/unit/CMakeLists.txt;47;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.iterator_support.transform_iterator2 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/transform_iterator2_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.iterator_support.transform_iterator2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/unit/CMakeLists.txt;47;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.iterator_support.zip_iterator "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/zip_iterator_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.iterator_support.zip_iterator PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/unit/CMakeLists.txt;47;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.iterator_support.is_sentinel_for "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/is_sentinel_for_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.iterator_support.is_sentinel_for PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/unit/CMakeLists.txt;47;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.iterator_support.is_sized_sentinel_for "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/is_sized_sentinel_for_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.iterator_support.is_sized_sentinel_for PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/unit/CMakeLists.txt;47;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/iterator_support/tests/unit/CMakeLists.txt;0;")
