# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/examples/1d_stencil
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/examples/1d_stencil
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.examples.1d_stencil.1d_stencil_1 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/1d_stencil_1" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.1d_stencil.1d_stencil_1 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/examples/1d_stencil/CMakeLists.txt;67;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/examples/1d_stencil/CMakeLists.txt;0;")
add_test(tests.examples.1d_stencil.1d_stencil_2 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/1d_stencil_2" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.1d_stencil.1d_stencil_2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/examples/1d_stencil/CMakeLists.txt;67;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/examples/1d_stencil/CMakeLists.txt;0;")
add_test(tests.examples.1d_stencil.1d_stencil_3 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/1d_stencil_3" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.1d_stencil.1d_stencil_3 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/examples/1d_stencil/CMakeLists.txt;67;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/examples/1d_stencil/CMakeLists.txt;0;")
add_test(tests.examples.1d_stencil.1d_stencil_4 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/1d_stencil_4" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.1d_stencil.1d_stencil_4 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/examples/1d_stencil/CMakeLists.txt;67;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/examples/1d_stencil/CMakeLists.txt;0;")
add_test(tests.examples.1d_stencil.1d_stencil_4_parallel "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/1d_stencil_4_parallel" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.1d_stencil.1d_stencil_4_parallel PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/examples/1d_stencil/CMakeLists.txt;67;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/examples/1d_stencil/CMakeLists.txt;0;")
add_test(tests.examples.1d_stencil.1d_stencil_5 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/1d_stencil_5" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.1d_stencil.1d_stencil_5 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/examples/1d_stencil/CMakeLists.txt;67;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/examples/1d_stencil/CMakeLists.txt;0;")
add_test(tests.examples.1d_stencil.1d_stencil_6 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/1d_stencil_6" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.1d_stencil.1d_stencil_6 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/examples/1d_stencil/CMakeLists.txt;67;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/examples/1d_stencil/CMakeLists.txt;0;")
add_test(tests.examples.1d_stencil.1d_stencil_7 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/1d_stencil_7" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.1d_stencil.1d_stencil_7 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/examples/1d_stencil/CMakeLists.txt;67;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/examples/1d_stencil/CMakeLists.txt;0;")
add_test(tests.examples.1d_stencil.1d_stencil_8 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/1d_stencil_8" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.1d_stencil.1d_stencil_8 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/examples/1d_stencil/CMakeLists.txt;67;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/examples/1d_stencil/CMakeLists.txt;0;")
add_test(tests.examples.1d_stencil.1d_stencil_channel "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/1d_stencil_channel" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.1d_stencil.1d_stencil_channel PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/examples/1d_stencil/CMakeLists.txt;67;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/examples/1d_stencil/CMakeLists.txt;0;")
