# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/tests/regressions/threads
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/tests/regressions/threads
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.regressions.threads.block_os_threads_1036 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/block_os_threads_1036_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.threads.block_os_threads_1036 PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/threads/CMakeLists.txt;45;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/threads/CMakeLists.txt;0;")
add_test(tests.regressions.threads.main_thread_exit_callbacks "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/main_thread_exit_callbacks_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.threads.main_thread_exit_callbacks PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/threads/CMakeLists.txt;45;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/threads/CMakeLists.txt;0;")
add_test(tests.regressions.threads.run_as_hpx_thread_exceptions_3304 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/run_as_hpx_thread_exceptions_3304_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.threads.run_as_hpx_thread_exceptions_3304 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/threads/CMakeLists.txt;45;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/threads/CMakeLists.txt;0;")
add_test(tests.regressions.threads.run_as_os_thread_lockup_2991 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/run_as_os_thread_lockup_2991_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.threads.run_as_os_thread_lockup_2991 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/threads/CMakeLists.txt;45;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/threads/CMakeLists.txt;0;")
add_test(tests.regressions.threads.stackless_self_4155 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/stackless_self_4155_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.threads.stackless_self_4155 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/threads/CMakeLists.txt;45;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/threads/CMakeLists.txt;0;")
add_test(tests.regressions.threads.thread_data_1111 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/thread_data_1111_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.threads.thread_data_1111 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/threads/CMakeLists.txt;45;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/threads/CMakeLists.txt;0;")
add_test(tests.regressions.threads.thread_rescheduling "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/thread_rescheduling_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.threads.thread_rescheduling PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/threads/CMakeLists.txt;45;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/threads/CMakeLists.txt;0;")
add_test(tests.regressions.threads.thread_suspend_pending "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/thread_suspend_pending_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.threads.thread_suspend_pending PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/threads/CMakeLists.txt;45;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/threads/CMakeLists.txt;0;")
add_test(tests.regressions.threads.thread_suspend_duration "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/thread_suspend_duration_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.threads.thread_suspend_duration PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/threads/CMakeLists.txt;45;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/threads/CMakeLists.txt;0;")
add_test(tests.regressions.threads.threads_all_1422 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/threads_all_1422_test" "-e" "0" "-t" "-1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.threads.threads_all_1422 PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/threads/CMakeLists.txt;45;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/threads/CMakeLists.txt;0;")
add_test(tests.regressions.threads.resume_priority "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/resume_priority_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.threads.resume_priority PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/threads/CMakeLists.txt;45;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/threads/CMakeLists.txt;0;")
