#!groovy

// Copyright (c) 2020 ETH Zurich
//
// SPDX-License-Identifier: BSL-1.0
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

pipeline {
    agent any
    environment {
        GITHUB_TOKEN = credentials('GITHUB_TOKEN')
    }
    stages {
        stage('checkout') {
            steps {
                dir('hpx') {
                    checkout scm
                    echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
                }
            }
        }
        stage('build') {
            matrix {
                axes {
                    axis {
                        name 'configuration_name'
                        values 'gcc-8', 'gcc-9', 'clang-7', 'clang-8', 'clang-9', 'gcc-9-cuda-11'
                    }
                    axis {
                         name 'build_type'
                         values 'Release', 'Debug'
                    }
                }
                stages {
                    stage('build') {
                        steps {
                            dir('hpx') {
                                sh '''
                                #!/bin/bash -l
                                .jenkins/lsu/entry.sh
                                '''
                            }
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'hpx/jenkins-hpx-*', fingerprint: true
            archiveArtifacts artifacts: 'hpx/build/*/Testing/**', fingerprint: true
        }
    }
}
