# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/full/agas/tests/regressions
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/full/agas/tests/regressions
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.regressions.modules.agas.duplicate_id_registration_1596 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/duplicate_id_registration_1596_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.agas.duplicate_id_registration_1596 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/agas/tests/regressions/CMakeLists.txt;32;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/agas/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.agas.id_type_ref_counting_1032 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/id_type_ref_counting_1032_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.agas.id_type_ref_counting_1032 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/agas/tests/regressions/CMakeLists.txt;32;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/agas/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.agas.pass_by_value_id_type_action "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/pass_by_value_id_type_action_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.agas.pass_by_value_id_type_action PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/agas/tests/regressions/CMakeLists.txt;32;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/agas/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.agas.send_gid_keep_component_1624 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/send_gid_keep_component_1624_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.agas.send_gid_keep_component_1624 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/agas/tests/regressions/CMakeLists.txt;32;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/agas/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.agas.distributed.tcp.register_with_basename_1804 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/register_with_basename_1804_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.regressions.modules.agas.distributed.tcp.register_with_basename_1804 PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/agas/tests/regressions/CMakeLists.txt;32;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/agas/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.id_type_ref_counting_1032_4 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/id_type_ref_counting_1032_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--" "PSEUDO_DEPS_NAME" "id_type_ref_counting_1032")
set_tests_properties(tests.regressions.id_type_ref_counting_1032_4 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;266;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/agas/tests/regressions/CMakeLists.txt;35;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/agas/tests/regressions/CMakeLists.txt;0;")
