# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/pack_traversal/tests/regressions
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/pack_traversal/tests/regressions
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.regressions.modules.pack_traversal.unwrapped_1528 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/unwrapped_1528_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.pack_traversal.unwrapped_1528 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/pack_traversal/tests/regressions/CMakeLists.txt;22;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/pack_traversal/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.pack_traversal.unwrapping_nullary_6045 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/unwrapping_nullary_6045_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.pack_traversal.unwrapping_nullary_6045 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/pack_traversal/tests/regressions/CMakeLists.txt;22;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/pack_traversal/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.pack_traversal.unwrapping_noncopyable "/opt/homebrew/bin/cmake" "--build" "/Users/harith/Desktop/Open Source/hpx/build2" "--target" "tests_regressions_modules_pack_traversal_unwrapping_noncopyable" "--config" "Release")
set_tests_properties(tests.regressions.modules.pack_traversal.unwrapping_noncopyable PROPERTIES  RUN_SERIAL "TRUE" WORKING_DIRECTORY "/Users/harith/Desktop/Open Source/hpx/build2" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;48;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;74;add_hpx_compile_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;86;add_test_and_deps_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/core/pack_traversal/tests/regressions/CMakeLists.txt;36;add_hpx_regression_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/core/pack_traversal/tests/regressions/CMakeLists.txt;0;")
