//  Copyright (c) 2019-2025 STE||AR Group
//
//  SPDX-License-Identifier: BSL-1.0
//  Distributed under the Boost Software License, Version 1.0. (See accompanying
//  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

// Do not edit this file! It has been generated by the cmake configuration step.

#pragma once

#include <hpx/config.hpp>

#if defined(HPX_HAVE_MODULE_DISTRIBUTION_POLICIES)
#include <hpx/distribution_policies/binpacking_distribution_policy.hpp>
#include <hpx/distribution_policies/colocating_distribution_policy.hpp>
#include <hpx/distribution_policies/container_distribution_policy.hpp>
#include <hpx/distribution_policies/default_distribution_policy.hpp>
#include <hpx/distribution_policies/explicit_container_distribution_policy.hpp>
#include <hpx/distribution_policies/target_distribution_policy.hpp>
#include <hpx/distribution_policies/unwrapping_result_policy.hpp>
#endif

