//  Copyright (c) 2019-2025 STE||AR Group
//
//  SPDX-License-Identifier: BSL-1.0
//  Distributed under the Boost Software License, Version 1.0. (See accompanying
//  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

// Do not edit this file! It has been generated by the cmake configuration step.

#pragma once

#include <hpx/config.hpp>

#if defined(HPX_HAVE_MODULE_THREAD_SUPPORT)
#include <hpx/thread_support/atomic_count.hpp>
#include <hpx/thread_support/set_thread_name.hpp>
#include <hpx/thread_support/spinlock.hpp>
#include <hpx/thread_support/thread_specific_ptr.hpp>
#include <hpx/thread_support/unlock_guard.hpp>
#endif

