# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/unseq_algorithms
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/algorithms/tests/unit/unseq_algorithms
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.unit.modules.algorithms.unseq_algorithms.foreach_unseq "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/foreach_unseq_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.algorithms.unseq_algorithms.foreach_unseq PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/unseq_algorithms/CMakeLists.txt;35;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/unseq_algorithms/CMakeLists.txt;0;")
add_test(tests.unit.modules.algorithms.unseq_algorithms.foreach_unseq_zipiter "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/foreach_unseq_zipiter_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.algorithms.unseq_algorithms.foreach_unseq_zipiter PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/unseq_algorithms/CMakeLists.txt;35;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/unseq_algorithms/CMakeLists.txt;0;")
add_test(tests.unit.modules.algorithms.unseq_algorithms.foreachn_unseq "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/foreachn_unseq_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.algorithms.unseq_algorithms.foreachn_unseq PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/unseq_algorithms/CMakeLists.txt;35;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/unseq_algorithms/CMakeLists.txt;0;")
add_test(tests.unit.modules.algorithms.unseq_algorithms.reduce_unseq "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/reduce_unseq_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.algorithms.unseq_algorithms.reduce_unseq PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/unseq_algorithms/CMakeLists.txt;35;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/unseq_algorithms/CMakeLists.txt;0;")
add_test(tests.unit.modules.algorithms.unseq_algorithms.transform_binary2_unseq "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/transform_binary2_unseq_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.algorithms.unseq_algorithms.transform_binary2_unseq PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/unseq_algorithms/CMakeLists.txt;35;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/unseq_algorithms/CMakeLists.txt;0;")
add_test(tests.unit.modules.algorithms.unseq_algorithms.transform_binary_unseq "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/transform_binary_unseq_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.algorithms.unseq_algorithms.transform_binary_unseq PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/unseq_algorithms/CMakeLists.txt;35;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/unseq_algorithms/CMakeLists.txt;0;")
add_test(tests.unit.modules.algorithms.unseq_algorithms.transform_reduce_binary_unseq "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/transform_reduce_binary_unseq_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.algorithms.unseq_algorithms.transform_reduce_binary_unseq PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/unseq_algorithms/CMakeLists.txt;35;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/unseq_algorithms/CMakeLists.txt;0;")
add_test(tests.unit.modules.algorithms.unseq_algorithms.transform_reduce_unseq "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/transform_reduce_unseq_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.algorithms.unseq_algorithms.transform_reduce_unseq PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/unseq_algorithms/CMakeLists.txt;35;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/unseq_algorithms/CMakeLists.txt;0;")
add_test(tests.unit.modules.algorithms.unseq_algorithms.transform_unseq "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/transform_unseq_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.algorithms.unseq_algorithms.transform_unseq PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/unseq_algorithms/CMakeLists.txt;35;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/unseq_algorithms/CMakeLists.txt;0;")
