//  Copyright (c) 2020-2025 STE||AR Group
//  Copyright (c) 2017-2022 Hartmut Kaiser
//
//  SPDX-License-Identifier: BSL-1.0
//  Distributed under the Boost Software License, Version 1.0. (See accompanying
//  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

// Do not edit this file! It has been generated by the cmake configuration step.

#include <hpx/modules/config_registry.hpp>

namespace hpx::serialization_cfg {

    config_registry::add_module_config_helper add_config{
    {
        "serialization",
        {
            "HPX_SERIALIZATION_WITH_ALLOW_CONST_TUPLE_MEMBERS=OFF",
            "HPX_SERIALIZATION_WITH_ALLOW_RAW_POINTER_SERIALIZATION=OFF",
            "HPX_SERIALIZATION_WITH_ALL_TYPES_ARE_BITWISE_SERIALIZABLE=OFF",
            "HPX_SERIALIZATION_WITH_BOOST_TYPES=OFF",
            "HPX_SERIALIZATION_WITH_SUPPORTS_ENDIANESS=OFF",
        }
    }};
}
