# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/examples
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/resiliency/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.examples.modules.resiliency.async_replay "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_replay" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.modules.resiliency.async_replay PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/examples/CMakeLists.txt;46;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/examples/CMakeLists.txt;0;")
add_test(tests.examples.modules.resiliency.async_replicate "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_replicate" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.modules.resiliency.async_replicate PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/examples/CMakeLists.txt;46;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/examples/CMakeLists.txt;0;")
add_test(tests.examples.modules.resiliency.async_replicate_vote "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_replicate_vote" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.modules.resiliency.async_replicate_vote PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/examples/CMakeLists.txt;46;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/examples/CMakeLists.txt;0;")
add_test(tests.examples.modules.resiliency.version "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/version" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.modules.resiliency.version PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/examples/CMakeLists.txt;46;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/examples/CMakeLists.txt;0;")
add_test(tests.examples.modules.resiliency.1d_stencil_replay_exception "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/1d_stencil_replay_exception" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.modules.resiliency.1d_stencil_replay_exception PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/examples/CMakeLists.txt;46;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/examples/CMakeLists.txt;0;")
add_test(tests.examples.modules.resiliency.1d_stencil_replay_validate "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/1d_stencil_replay_validate" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.modules.resiliency.1d_stencil_replay_validate PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/examples/CMakeLists.txt;46;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/examples/CMakeLists.txt;0;")
add_test(tests.examples.modules.resiliency.dataflow_replicate "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/dataflow_replicate" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.modules.resiliency.dataflow_replicate PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/examples/CMakeLists.txt;46;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resiliency/examples/CMakeLists.txt;0;")
