# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/examples/transpose
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/examples/transpose
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.examples.transpose.transpose_serial "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/transpose_serial" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.transpose.transpose_serial PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/examples/transpose/CMakeLists.txt;47;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/examples/transpose/CMakeLists.txt;0;")
add_test(tests.examples.transpose.transpose_serial_block "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/transpose_serial_block" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.transpose.transpose_serial_block PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/examples/transpose/CMakeLists.txt;47;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/examples/transpose/CMakeLists.txt;0;")
add_test(tests.examples.transpose.transpose_smp "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/transpose_smp" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.transpose.transpose_smp PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/examples/transpose/CMakeLists.txt;47;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/examples/transpose/CMakeLists.txt;0;")
add_test(tests.examples.transpose.transpose_smp_block "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/transpose_smp_block" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.transpose.transpose_smp_block PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/examples/transpose/CMakeLists.txt;47;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/examples/transpose/CMakeLists.txt;0;")
add_test(tests.examples.transpose.transpose_block "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/transpose_block" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.transpose.transpose_block PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/examples/transpose/CMakeLists.txt;47;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/examples/transpose/CMakeLists.txt;0;")
add_test(tests.examples.transpose.transpose_serial_vector "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/transpose_serial_vector" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.transpose.transpose_serial_vector PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/examples/transpose/CMakeLists.txt;47;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/examples/transpose/CMakeLists.txt;0;")
