# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/datastructures/tests/regressions
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/datastructures/tests/regressions
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.regressions.modules.datastructures.non_default_constructible_tuple_5886 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/non_default_constructible_tuple_5886_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.datastructures.non_default_constructible_tuple_5886 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/datastructures/tests/regressions/CMakeLists.txt;24;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/datastructures/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.datastructures.optional_swap_3200 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/optional_swap_3200_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.datastructures.optional_swap_3200 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/datastructures/tests/regressions/CMakeLists.txt;24;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/datastructures/tests/regressions/CMakeLists.txt;0;")
