# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/full/collectives/tests/regressions
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/full/collectives/tests/regressions
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.regressions.modules.collectives.all_reduce_vector_bool "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/all_reduce_vector_bool_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.collectives.all_reduce_vector_bool PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/collectives/tests/regressions/CMakeLists.txt;46;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/collectives/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.collectives.distributed.tcp.barrier_3792 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/barrier_3792_test" "-e" "0" "-t" "1" "-l" "3" "-p" "tcp" "-v" "--")
set_tests_properties(tests.regressions.modules.collectives.distributed.tcp.barrier_3792 PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/collectives/tests/regressions/CMakeLists.txt;46;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/collectives/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.collectives.barrier_hang "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/barrier_hang_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.collectives.barrier_hang PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/collectives/tests/regressions/CMakeLists.txt;46;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/collectives/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.collectives.distributed.tcp.broadcast_unwrap_future_2885 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/broadcast_unwrap_future_2885_test" "-e" "0" "-t" "4" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.regressions.modules.collectives.distributed.tcp.broadcast_unwrap_future_2885 PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/collectives/tests/regressions/CMakeLists.txt;46;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/collectives/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.collectives.distributed.tcp.broadcast_wait_for_2822 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/broadcast_wait_for_2822_test" "-e" "0" "-t" "4" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.regressions.modules.collectives.distributed.tcp.broadcast_wait_for_2822 PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/collectives/tests/regressions/CMakeLists.txt;46;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/collectives/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.collectives.distributed.tcp.collectives_bool_5940 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/collectives_bool_5940_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.regressions.modules.collectives.distributed.tcp.collectives_bool_5940 PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/collectives/tests/regressions/CMakeLists.txt;46;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/collectives/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.collectives.distributed.tcp.exclusive_scan_6636 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/exclusive_scan_6636_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.regressions.modules.collectives.distributed.tcp.exclusive_scan_6636 PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/collectives/tests/regressions/CMakeLists.txt;46;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/collectives/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.collectives.distributed.tcp.multiple_gather_ops_2001 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/multiple_gather_ops_2001_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.regressions.modules.collectives.distributed.tcp.multiple_gather_ops_2001 PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/collectives/tests/regressions/CMakeLists.txt;46;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/collectives/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.collectives.reduce_vector_bool "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/reduce_vector_bool_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.collectives.reduce_vector_bool PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/collectives/tests/regressions/CMakeLists.txt;46;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/collectives/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.collectives.trivially_copyable_all_gather "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/trivially_copyable_all_gather_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.collectives.trivially_copyable_all_gather PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/collectives/tests/regressions/CMakeLists.txt;46;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/collectives/tests/regressions/CMakeLists.txt;0;")
