# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/full/resiliency_distributed/tests/performance/replay
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/full/resiliency_distributed/tests/performance/replay
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.performance.modules.resiliency_distributed.replay.distributed.tcp.1d_stencil_distributed "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/1d_stencil_distributed_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.performance.modules.resiliency_distributed.replay.distributed.tcp.1d_stencil_distributed PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;286;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/resiliency_distributed/tests/performance/replay/CMakeLists.txt;40;add_hpx_performance_test;/Users/harith/Desktop/Open Source/hpx/libs/full/resiliency_distributed/tests/performance/replay/CMakeLists.txt;0;")
add_test(tests.performance.modules.resiliency_distributed.replay.distributed.tcp.1d_stencil_replay_distributed "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/1d_stencil_replay_distributed_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.performance.modules.resiliency_distributed.replay.distributed.tcp.1d_stencil_replay_distributed PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;286;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/resiliency_distributed/tests/performance/replay/CMakeLists.txt;40;add_hpx_performance_test;/Users/harith/Desktop/Open Source/hpx/libs/full/resiliency_distributed/tests/performance/replay/CMakeLists.txt;0;")
add_test(tests.performance.modules.resiliency_distributed.replay.distributed.tcp.async_replay_distributed "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_replay_distributed_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.performance.modules.resiliency_distributed.replay.distributed.tcp.async_replay_distributed PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;286;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/resiliency_distributed/tests/performance/replay/CMakeLists.txt;40;add_hpx_performance_test;/Users/harith/Desktop/Open Source/hpx/libs/full/resiliency_distributed/tests/performance/replay/CMakeLists.txt;0;")
add_test(tests.performance.modules.resiliency_distributed.replay.distributed.tcp.async_replay_distributed_validate "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_replay_distributed_validate_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.performance.modules.resiliency_distributed.replay.distributed.tcp.async_replay_distributed_validate PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;286;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/resiliency_distributed/tests/performance/replay/CMakeLists.txt;40;add_hpx_performance_test;/Users/harith/Desktop/Open Source/hpx/libs/full/resiliency_distributed/tests/performance/replay/CMakeLists.txt;0;")
add_test(tests.performance.modules.resiliency_distributed.replay.distributed.tcp.plain_async_distributed "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/plain_async_distributed_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.performance.modules.resiliency_distributed.replay.distributed.tcp.plain_async_distributed PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;286;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/resiliency_distributed/tests/performance/replay/CMakeLists.txt;40;add_hpx_performance_test;/Users/harith/Desktop/Open Source/hpx/libs/full/resiliency_distributed/tests/performance/replay/CMakeLists.txt;0;")
