# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/full/runtime_distributed/tests/regressions
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/full/runtime_distributed/tests/regressions
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.regressions.modules.runtime_distributed.multiple_init "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/multiple_init_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.runtime_distributed.multiple_init PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/runtime_distributed/tests/regressions/CMakeLists.txt;25;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/runtime_distributed/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.runtime_distributed.multiple_init_2918 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/multiple_init_2918_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.runtime_distributed.multiple_init_2918 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/runtime_distributed/tests/regressions/CMakeLists.txt;25;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/runtime_distributed/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.runtime_distributed.unhandled_exception_582 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/unhandled_exception_582_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.runtime_distributed.unhandled_exception_582 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/runtime_distributed/tests/regressions/CMakeLists.txt;25;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/runtime_distributed/tests/regressions/CMakeLists.txt;0;")
