//  Copyright (c) 2019-2025 STE||AR Group
//
//  SPDX-License-Identifier: BSL-1.0
//  Distributed under the Boost Software License, Version 1.0. (See accompanying
//  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

// Do not edit this file! It has been generated by the cmake configuration step.

#pragma once

#include <hpx/config.hpp>

#if defined(HPX_HAVE_MODULE_COMPONENTS_BASE)
#include <hpx/components_base/agas_interface.hpp>
#include <hpx/components_base/get_lva.hpp>
#include <hpx/components_base/components_base_fwd.hpp>
#include <hpx/components_base/component_type.hpp>
#include <hpx/components_base/component_commandline.hpp>
#include <hpx/components_base/component_startup_shutdown.hpp>
#include <hpx/components_base/generate_unique_ids.hpp>
#include <hpx/components_base/pinned_ptr.hpp>
#include <hpx/components_base/server/abstract_component_base.hpp>
#include <hpx/components_base/server/abstract_migration_support.hpp>
#include <hpx/components_base/server/component.hpp>
#include <hpx/components_base/server/component_base.hpp>
#include <hpx/components_base/server/component_heap.hpp>
#include <hpx/components_base/server/create_component.hpp>
#include <hpx/components_base/server/create_component_fwd.hpp>
#include <hpx/components_base/server/fixed_component_base.hpp>
#include <hpx/components_base/server/locking_hook.hpp>
#include <hpx/components_base/server/managed_component_base.hpp>
#include <hpx/components_base/server/migration_support.hpp>
#include <hpx/components_base/server/one_size_heap_list.hpp>
#include <hpx/components_base/server/wrapper_heap.hpp>
#include <hpx/components_base/server/wrapper_heap_base.hpp>
#include <hpx/components_base/server/wrapper_heap_list.hpp>
#include <hpx/components_base/stub_base.hpp>
#include <hpx/components_base/traits/action_decorate_function.hpp>
#include <hpx/components_base/traits/component_config_data.hpp>
#include <hpx/components_base/traits/component_heap_type.hpp>
#include <hpx/components_base/traits/component_pin_support.hpp>
#include <hpx/components_base/traits/component_supports_migration.hpp>
#include <hpx/components_base/traits/component_type_is_compatible.hpp>
#include <hpx/components_base/traits/component_type_database.hpp>
#include <hpx/components_base/traits/is_component.hpp>
#include <hpx/components_base/traits/managed_component_policies.hpp>
#endif

