#!groovy

// Copyright (c) 2020 ETH Zurich
//
// SPDX-License-Identifier: BSL-1.0
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

pipeline {
    agent {
        node {
            label 'ssl_daintvm1'
        }
    }
    options {
        buildDiscarder(
            logRotator(
                daysToKeepStr: "14",
                numToKeepStr: "50",
                artifactDaysToKeepStr: "14",
                artifactNumToKeepStr: "50"
            )
        )
    }
    environment {
        CHECKOUT_DIR = "/dev/shm/${env.BUILD_TAG}/hpx"
        SPACK_ROOT = '/apps/daint/SSL/HPX/spack'
        GITHUB_TOKEN = credentials('STELLARBOT_GITHUB_TOKEN')
    }
    stages {
        stage('checkout') {
            steps {
                dir("${CHECKOUT_DIR}") {
                    checkout scm
                    echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
                }
            }
        }
        stage('build') {
            matrix {
                axes {
                    axis {
                        name 'configuration_name'
                        values 'gcc-11', 'gcc-10' //, 'gcc-7', 'gcc-cuda', 'clang-13', 'clang-12', 'clang-10', 'clang-9', 'clang-8', 'clang-7', 'clang-cuda', 'clang-apex'
                    }
                    axis {
                         name 'build_type'
                         values 'Release' //, 'Debug'
                    }
                }
                stages {
                    stage('build') {
                        steps {
                            dir("${CHECKOUT_DIR}") {
                                sh '''
                                #!/bin/bash -l
                                .jenkins/cscs/entry.sh
                                '''
                            }
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: '${CHECKOUT_DIR}/jenkins-hpx-*', fingerprint: true
            archiveArtifacts artifacts: '${CHECKOUT_DIR}/*-Testing/**', fingerprint: true
            sh '''
            #!/bin/sh
            rm -rfv ${CHECKOUT_DIR}
            '''
        }
    }
}
