# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/tests/regressions/lcos
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/tests/regressions/lcos
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.regressions.lcos.distributed.tcp.after_588 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/after_588_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.regressions.lcos.distributed.tcp.after_588 PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/lcos/CMakeLists.txt;45;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/lcos/CMakeLists.txt;0;")
add_test(tests.regressions.lcos.call_promise_get_gid_more_than_once "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/call_promise_get_gid_more_than_once_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.lcos.call_promise_get_gid_more_than_once PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/lcos/CMakeLists.txt;45;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/lcos/CMakeLists.txt;0;")
add_test(tests.regressions.lcos.distributed.tcp.lifetime_588 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/lifetime_588_test" "-e" "0" "-t" "2" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.regressions.lcos.distributed.tcp.lifetime_588 PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/lcos/CMakeLists.txt;45;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/lcos/CMakeLists.txt;0;")
add_test(tests.regressions.lcos.distributed.tcp.lifetime_588_1 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/lifetime_588_1_test" "-e" "0" "-t" "2" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.regressions.lcos.distributed.tcp.lifetime_588_1 PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/lcos/CMakeLists.txt;45;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/lcos/CMakeLists.txt;0;")
add_test(tests.regressions.lcos.promise_leak_996 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/promise_leak_996_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.lcos.promise_leak_996 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/lcos/CMakeLists.txt;45;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/lcos/CMakeLists.txt;0;")
add_test(tests.regressions.lcos.promise_1620 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/promise_1620_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.lcos.promise_1620 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/lcos/CMakeLists.txt;45;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/lcos/CMakeLists.txt;0;")
add_test(tests.regressions.lcos.distributed.tcp.receive_buffer_1733 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/receive_buffer_1733_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.regressions.lcos.distributed.tcp.receive_buffer_1733 PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/lcos/CMakeLists.txt;45;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/lcos/CMakeLists.txt;0;")
add_test(tests.regressions.lcos.shared_stated_leaked_1211 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/shared_stated_leaked_1211_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.lcos.shared_stated_leaked_1211 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/lcos/CMakeLists.txt;45;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/lcos/CMakeLists.txt;0;")
add_test(tests.regressions.lcos.sliding_semaphore_2338 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/sliding_semaphore_2338_test" "-e" "0" "-t" "2" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.lcos.sliding_semaphore_2338 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/lcos/CMakeLists.txt;45;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/lcos/CMakeLists.txt;0;")
add_test(tests.regressions.lcos.wait_for_action_2796 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/wait_for_action_2796_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.lcos.wait_for_action_2796 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/lcos/CMakeLists.txt;45;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/lcos/CMakeLists.txt;0;")
add_test(tests.regressions.lcos.distributed.tcp.after_588_4 "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/after_588_test" "-e" "0" "-t" "4" "-l" "2" "-p" "tcp" "-v" "--" "PSEUDO_DEPS_NAME" "after_588")
set_tests_properties(tests.regressions.lcos.distributed.tcp.after_588_4 PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/lcos/CMakeLists.txt;50;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/tests/regressions/lcos/CMakeLists.txt;0;")
