# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/synchronization/tests/performance
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/synchronization/tests/performance
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.performance.modules.synchronization.channel_mpmc_throughput "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/channel_mpmc_throughput_test" "-e" "0" "-t" "2" "-l" "1" "-v" "--")
set_tests_properties(tests.performance.modules.synchronization.channel_mpmc_throughput PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;286;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/synchronization/tests/performance/CMakeLists.txt;30;add_hpx_performance_test;/Users/harith/Desktop/Open Source/hpx/libs/core/synchronization/tests/performance/CMakeLists.txt;0;")
add_test(tests.performance.modules.synchronization.channel_mpsc_throughput "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/channel_mpsc_throughput_test" "-e" "0" "-t" "2" "-l" "1" "-v" "--")
set_tests_properties(tests.performance.modules.synchronization.channel_mpsc_throughput PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;286;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/synchronization/tests/performance/CMakeLists.txt;30;add_hpx_performance_test;/Users/harith/Desktop/Open Source/hpx/libs/core/synchronization/tests/performance/CMakeLists.txt;0;")
add_test(tests.performance.modules.synchronization.channel_spsc_throughput "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/channel_spsc_throughput_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.performance.modules.synchronization.channel_spsc_throughput PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;286;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/synchronization/tests/performance/CMakeLists.txt;30;add_hpx_performance_test;/Users/harith/Desktop/Open Source/hpx/libs/core/synchronization/tests/performance/CMakeLists.txt;0;")
