# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/full/async_distributed/tests/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.unit.modules.async_distributed.distributed.tcp.async_cb_remote "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_cb_remote_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.unit.modules.async_distributed.distributed.tcp.async_cb_remote PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/CMakeLists.txt;61;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.async_distributed.distributed.tcp.async_cb_remote_client "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_cb_remote_client_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.unit.modules.async_distributed.distributed.tcp.async_cb_remote_client PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/CMakeLists.txt;61;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.async_distributed.distributed.tcp.async_continue "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_continue_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.unit.modules.async_distributed.distributed.tcp.async_continue PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/CMakeLists.txt;61;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.async_distributed.distributed.tcp.async_continue_cb "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_continue_cb_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.unit.modules.async_distributed.distributed.tcp.async_continue_cb PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/CMakeLists.txt;61;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.async_distributed.distributed.tcp.async_remote "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_remote_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.unit.modules.async_distributed.distributed.tcp.async_remote PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/CMakeLists.txt;61;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.async_distributed.distributed.tcp.async_remote_client "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_remote_client_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.unit.modules.async_distributed.distributed.tcp.async_remote_client PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/CMakeLists.txt;61;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.async_distributed.async_unwrap_result "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_unwrap_result_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.async_distributed.async_unwrap_result PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/CMakeLists.txt;61;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.async_distributed.distributed.tcp.post_remote "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/post_remote_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.unit.modules.async_distributed.distributed.tcp.post_remote PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/CMakeLists.txt;61;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.async_distributed.distributed.tcp.post_remote_client "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/post_remote_client_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.unit.modules.async_distributed.distributed.tcp.post_remote_client PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/CMakeLists.txt;61;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.async_distributed.distributed.tcp.remote_dataflow "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/remote_dataflow_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.unit.modules.async_distributed.distributed.tcp.remote_dataflow PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/CMakeLists.txt;61;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.async_distributed.sync_remote "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/sync_remote_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.async_distributed.sync_remote PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/CMakeLists.txt;61;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/CMakeLists.txt;0;")
subdirs("actions")
subdirs("util")
