# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/full/async_colocated/tests/unit
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/full/async_colocated/tests/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.unit.modules.async_colocated.distributed.tcp.post_colocated "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/post_colocated_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.unit.modules.async_colocated.distributed.tcp.post_colocated PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_colocated/tests/unit/CMakeLists.txt;30;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_colocated/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.async_colocated.distributed.tcp.async_cb_colocated "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_cb_colocated_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.unit.modules.async_colocated.distributed.tcp.async_cb_colocated PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_colocated/tests/unit/CMakeLists.txt;30;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_colocated/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.async_colocated.async_colocated "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_colocated_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.async_colocated.async_colocated PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_colocated/tests/unit/CMakeLists.txt;30;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_colocated/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.async_colocated.distributed.tcp.async_continue_cb_colocated "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_continue_cb_colocated_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.unit.modules.async_colocated.distributed.tcp.async_continue_cb_colocated PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_colocated/tests/unit/CMakeLists.txt;30;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_colocated/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.async_colocated.async_continue_colocated "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_continue_colocated_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.async_colocated.async_continue_colocated PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_colocated/tests/unit/CMakeLists.txt;30;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_colocated/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.async_colocated.distributed.tcp.new_colocated "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/new_colocated_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.unit.modules.async_colocated.distributed.tcp.new_colocated PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_colocated/tests/unit/CMakeLists.txt;30;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_colocated/tests/unit/CMakeLists.txt;0;")
