# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/full/actions/tests/unit
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/full/actions/tests/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.unit.modules.actions.set_thread_state "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/set_thread_state_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.actions.set_thread_state PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/actions/tests/unit/CMakeLists.txt;37;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/actions/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.actions.thread_affinity "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/thread_affinity_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.actions.thread_affinity PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/actions/tests/unit/CMakeLists.txt;37;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/actions/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.actions.distributed.tcp.thread_stacksize "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/thread_stacksize_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.unit.modules.actions.distributed.tcp.thread_stacksize PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/actions/tests/unit/CMakeLists.txt;37;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/actions/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.actions.distributed.tcp.serialize_buffer "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/serialize_buffer_test" "-e" "0" "-t" "2" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.unit.modules.actions.distributed.tcp.serialize_buffer PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/actions/tests/unit/CMakeLists.txt;37;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/actions/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.actions.zero_copy_serialization "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/zero_copy_serialization_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.actions.zero_copy_serialization PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/actions/tests/unit/CMakeLists.txt;37;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/actions/tests/unit/CMakeLists.txt;0;")
