# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/functional/tests/regressions
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/functional/tests/regressions
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.regressions.modules.functional.bind_sfinae_5488 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/bind_sfinae_5488_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.functional.bind_sfinae_5488 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/functional/tests/regressions/CMakeLists.txt;22;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/functional/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.functional.is_callable_1179 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/is_callable_1179_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.functional.is_callable_1179 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/functional/tests/regressions/CMakeLists.txt;22;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/functional/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.functional.protect_with_nullary_pfo "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/protect_with_nullary_pfo_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.functional.protect_with_nullary_pfo PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/functional/tests/regressions/CMakeLists.txt;22;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/functional/tests/regressions/CMakeLists.txt;0;")
