# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/regressions
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/resource_partitioner/tests/regressions
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.regressions.modules.resource_partitioner.help_exit_4317_1 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/help_exit_4317_1_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.resource_partitioner.help_exit_4317_1 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/regressions/CMakeLists.txt;23;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.resource_partitioner.help_exit_4317_2 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/help_exit_4317_2_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.resource_partitioner.help_exit_4317_2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/regressions/CMakeLists.txt;23;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/regressions/CMakeLists.txt;0;")
