//  Copyright (c) 2019-2025 STE||AR Group
//
//  SPDX-License-Identifier: BSL-1.0
//  Distributed under the Boost Software License, Version 1.0. (See accompanying
//  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

// Do not edit this file! It has been generated by the cmake configuration step.

#pragma once

#include <hpx/config.hpp>

#if defined(HPX_HAVE_MODULE_ASYNC_COLOCATED)
#include <hpx/async_colocated/async_colocated_callback_fwd.hpp>
#include <hpx/async_colocated/async_colocated_callback.hpp>
#include <hpx/async_colocated/async_colocated_fwd.hpp>
#include <hpx/async_colocated/async_colocated.hpp>
#include <hpx/async_colocated/post_colocated_callback_fwd.hpp>
#include <hpx/async_colocated/post_colocated_callback.hpp>
#include <hpx/async_colocated/post_colocated_fwd.hpp>
#include <hpx/async_colocated/post_colocated.hpp>
#include <hpx/async_colocated/functional/colocated_helpers.hpp>
#include <hpx/async_colocated/get_colocation_id.hpp>
#include <hpx/async_colocated/register_post_colocated.hpp>
#include <hpx/async_colocated/server/destroy_component.hpp>
#endif

