# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/full/lcos_distributed/tests/regressions
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/full/lcos_distributed/tests/regressions
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.regressions.modules.lcos_distributed.channel_2916 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/channel_2916_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.lcos_distributed.channel_2916 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/lcos_distributed/tests/regressions/CMakeLists.txt;27;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/lcos_distributed/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.lcos_distributed.channel_not_empty_2890 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/channel_not_empty_2890_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.lcos_distributed.channel_not_empty_2890 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/lcos_distributed/tests/regressions/CMakeLists.txt;27;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/lcos_distributed/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.lcos_distributed.channel_register_as_2722 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/channel_register_as_2722_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.lcos_distributed.channel_register_as_2722 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/lcos_distributed/tests/regressions/CMakeLists.txt;27;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/lcos_distributed/tests/regressions/CMakeLists.txt;0;")
