# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/examples/async_io
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/examples/async_io
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.examples.async_io.async_io_simple "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_io_simple" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.async_io.async_io_simple PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/examples/async_io/CMakeLists.txt;38;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/examples/async_io/CMakeLists.txt;0;")
add_test(tests.examples.async_io.async_io_action "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_io_action" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.async_io.async_io_action PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/examples/async_io/CMakeLists.txt;38;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/examples/async_io/CMakeLists.txt;0;")
add_test(tests.examples.async_io.async_io_external "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_io_external" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.async_io.async_io_external PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/examples/async_io/CMakeLists.txt;38;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/examples/async_io/CMakeLists.txt;0;")
add_test(tests.examples.async_io.async_io_low_level "/Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13" "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_io_low_level" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.async_io.async_io_low_level PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/examples/async_io/CMakeLists.txt;38;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/examples/async_io/CMakeLists.txt;0;")
