//  Copyright (c) 2019-2025 STE||AR Group
//
//  SPDX-License-Identifier: BSL-1.0
//  Distributed under the Boost Software License, Version 1.0. (See accompanying
//  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

// Do not edit this file! It has been generated by the cmake configuration step.

#pragma once

#include <hpx/config.hpp>

#if defined(HPX_HAVE_MODULE_SERIALIZATION)
#include <hpx/serialization.hpp>
#include <hpx/serialization/detail/allow_zero_copy_receive.hpp>
#include <hpx/serialization/array.hpp>
#include <hpx/serialization/bitset.hpp>
#include <hpx/serialization/complex.hpp>
#include <hpx/serialization/datapar.hpp>
#include <hpx/serialization/deque.hpp>
#include <hpx/serialization/exception_ptr.hpp>
#include <hpx/serialization/list.hpp>
#include <hpx/serialization/map.hpp>
#include <hpx/serialization/set.hpp>
#include <hpx/serialization/serialize_buffer_fwd.hpp>
#include <hpx/serialization/serialize_buffer.hpp>
#include <hpx/serialization/string.hpp>
#include <hpx/serialization/std_tuple.hpp>
#include <hpx/serialization/unordered_map.hpp>
#include <hpx/serialization/vector.hpp>
#include <hpx/serialization/variant.hpp>
#include <hpx/serialization/valarray.hpp>
#include <hpx/serialization/shared_ptr.hpp>
#include <hpx/serialization/unique_ptr.hpp>
#include <hpx/serialization/access.hpp>
#include <hpx/serialization/base_object.hpp>
#include <hpx/serialization/basic_archive.hpp>
#include <hpx/serialization/binary_filter.hpp>
#include <hpx/serialization/brace_initializable.hpp>
#include <hpx/serialization/brace_initializable_fwd.hpp>
#include <hpx/serialization/container.hpp>
#include <hpx/serialization/input_archive.hpp>
#include <hpx/serialization/input_container.hpp>
#include <hpx/serialization/output_archive.hpp>
#include <hpx/serialization/output_container.hpp>
#include <hpx/serialization/serialization_chunk.hpp>
#include <hpx/serialization/serialization_fwd.hpp>
#include <hpx/serialization/serialize.hpp>
#include <hpx/serialization/traits/brace_initializable_traits.hpp>
#include <hpx/serialization/traits/is_bitwise_serializable.hpp>
#include <hpx/serialization/traits/is_not_bitwise_serializable.hpp>
#include <hpx/serialization/traits/is_serializable.hpp>
#include <hpx/serialization/traits/needs_automatic_registration.hpp>
#include <hpx/serialization/traits/polymorphic_traits.hpp>
#include <hpx/serialization/traits/serialization_access_data.hpp>
#endif

