# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/resource_partitioner/tests/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.unit.modules.resource_partitioner.background_scheduler "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/background_scheduler_test" "-e" "0" "-t" "2" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.resource_partitioner.background_scheduler PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;69;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.resource_partitioner.cross_pool_injection "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/cross_pool_injection_test" "-e" "0" "-t" "-1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.resource_partitioner.cross_pool_injection PROPERTIES  RUN_SERIAL "TRUE" TIMEOUT "300" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;69;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.resource_partitioner.named_pool_executor "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/named_pool_executor_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.resource_partitioner.named_pool_executor PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;69;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.resource_partitioner.resource_partitioner_info "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/resource_partitioner_info_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.resource_partitioner.resource_partitioner_info PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;69;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.resource_partitioner.scheduler_binding_check "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/scheduler_binding_check_test" "-e" "0" "-t" "-1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.resource_partitioner.scheduler_binding_check PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;69;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.resource_partitioner.scheduler_priority_check "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/scheduler_priority_check_test" "-e" "0" "-t" "-1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.resource_partitioner.scheduler_priority_check PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;69;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.resource_partitioner.shutdown_suspended_pus "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/shutdown_suspended_pus_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.resource_partitioner.shutdown_suspended_pus PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;69;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.resource_partitioner.suspend_disabled "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/suspend_disabled_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.resource_partitioner.suspend_disabled PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;69;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.resource_partitioner.suspend_pool "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/suspend_pool_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.resource_partitioner.suspend_pool PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;69;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.resource_partitioner.suspend_pool_external "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/suspend_pool_external_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.resource_partitioner.suspend_pool_external PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;69;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.resource_partitioner.suspend_runtime "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/suspend_runtime_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.resource_partitioner.suspend_runtime PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;69;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.resource_partitioner.suspend_thread "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/suspend_thread_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.resource_partitioner.suspend_thread PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;69;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.resource_partitioner.suspend_thread_external "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/suspend_thread_external_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.resource_partitioner.suspend_thread_external PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;69;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.resource_partitioner.used_pus "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/used_pus_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.resource_partitioner.used_pus PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;69;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/tests/unit/CMakeLists.txt;0;")
