//  Copyright (c) 2020-2025 STE||AR Group
//
//  SPDX-License-Identifier: BSL-1.0
//  Distributed under the Boost Software License, Version 1.0. (See accompanying
//  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

// Do not edit this file! It has been generated by the cmake configuration step.

#pragma once

#include <hpx/config.hpp>
#include <hpx/agas_base/config/defines.hpp>
#include <hpx/modules/agas_base.hpp>

#if HPX_HAVE_DEPRECATION_WARNINGS
#if defined(HPX_MSVC)
#pragma message("The header hpx/runtime/agas/symbol_namespace.hpp is deprecated, " \
    "please include hpx/modules/agas_base.hpp instead." \
    "To disable this warning, please define HPX_HAVE_DEPRECATION_WARNINGS=0.")
#else
#warning "The header hpx/runtime/agas/symbol_namespace.hpp is deprecated, " \
    "please include hpx/modules/agas_base.hpp instead" \
    "To disable this warning, please define HPX_HAVE_DEPRECATION_WARNINGS=0."
#endif
#endif
