#!/bin/bash
#PBS -N multilocality_tests.cpi_test
#PBS -l walltime=00:10:00,nodes=32:ppn=8
#PBS -q workq

# Make sure this matches your hpx_run install directory!
export HPX_RUN=$HOME/projects/parallex_svn/projects/hpx_run

cd $HOME
echo Job $PBS_JOBNAME is executing in `pwd` with $PBS_NODEFILE as the node file:
echo $PATH
echo $LD_LIBRARY_PATH
date
for T in 1 2 4 8; do 
  for L in 1 2 4 8 16 32; do
    echo "Running with -l $L:$T"
    python $HPX_RUN/hpx_run.py -m $PBS_NODEFILE -l $L:$T "cpi_test --throws=1000000 --granularity=$T" -s;
  done;
done
date

