# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/full/actions/tests/regressions
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/full/actions/tests/regressions
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.regressions.modules.actions.distributed.tcp.non_default_constructible_argument_5998 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/non_default_constructible_argument_5998_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--")
set_tests_properties(tests.regressions.modules.actions.distributed.tcp.non_default_constructible_argument_5998 PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/actions/tests/regressions/CMakeLists.txt;39;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/actions/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.actions.tuple_serialization_803 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/tuple_serialization_803_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.actions.tuple_serialization_803 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/actions/tests/regressions/CMakeLists.txt;39;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/actions/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.actions.function_argument "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/function_argument_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.actions.function_argument PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/actions/tests/regressions/CMakeLists.txt;39;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/actions/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.actions.wait_all_hang_1946 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/wait_all_hang_1946_test" "-e" "0" "-t" "8" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.actions.wait_all_hang_1946 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/actions/tests/regressions/CMakeLists.txt;39;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/actions/tests/regressions/CMakeLists.txt;0;")
