# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/actions
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/full/async_distributed/tests/unit/actions
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.unit.modules.async_distributed.return_future "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/return_future_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.async_distributed.return_future PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/actions/CMakeLists.txt;24;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/actions/CMakeLists.txt;0;")
add_test(tests.unit.modules.async_distributed.succeed_compile_const_ref_argument "/opt/homebrew/bin/cmake" "--build" "/Users/harith/Desktop/Open Source/hpx/build2" "--target" "tests_unit_modules_async_distributed_succeed_compile_const_ref_argument" "--config" "Release")
set_tests_properties(tests.unit.modules.async_distributed.succeed_compile_const_ref_argument PROPERTIES  RUN_SERIAL "TRUE" WORKING_DIRECTORY "/Users/harith/Desktop/Open Source/hpx/build2" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;48;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;74;add_hpx_compile_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;82;add_test_and_deps_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/actions/CMakeLists.txt;51;add_hpx_unit_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/actions/CMakeLists.txt;0;")
add_test(tests.unit.modules.async_distributed.succeed_compile_rvalue_ref_argument "/opt/homebrew/bin/cmake" "--build" "/Users/harith/Desktop/Open Source/hpx/build2" "--target" "tests_unit_modules_async_distributed_succeed_compile_rvalue_ref_argument" "--config" "Release")
set_tests_properties(tests.unit.modules.async_distributed.succeed_compile_rvalue_ref_argument PROPERTIES  RUN_SERIAL "TRUE" WORKING_DIRECTORY "/Users/harith/Desktop/Open Source/hpx/build2" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;48;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;74;add_hpx_compile_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;82;add_test_and_deps_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/actions/CMakeLists.txt;51;add_hpx_unit_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/actions/CMakeLists.txt;0;")
add_test(tests.unit.modules.async_distributed.fail_compile_non_const_array_argument "/opt/homebrew/bin/cmake" "--build" "/Users/harith/Desktop/Open Source/hpx/build2" "--target" "tests_unit_modules_async_distributed_fail_compile_non_const_array_argument" "--config" "Release")
set_tests_properties(tests.unit.modules.async_distributed.fail_compile_non_const_array_argument PROPERTIES  RUN_SERIAL "TRUE" WILL_FAIL "TRUE" WORKING_DIRECTORY "/Users/harith/Desktop/Open Source/hpx/build2" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;48;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;74;add_hpx_compile_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;82;add_test_and_deps_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/actions/CMakeLists.txt;51;add_hpx_unit_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/actions/CMakeLists.txt;0;")
add_test(tests.unit.modules.async_distributed.fail_compile_const_array_argument "/opt/homebrew/bin/cmake" "--build" "/Users/harith/Desktop/Open Source/hpx/build2" "--target" "tests_unit_modules_async_distributed_fail_compile_const_array_argument" "--config" "Release")
set_tests_properties(tests.unit.modules.async_distributed.fail_compile_const_array_argument PROPERTIES  RUN_SERIAL "TRUE" WILL_FAIL "TRUE" WORKING_DIRECTORY "/Users/harith/Desktop/Open Source/hpx/build2" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;48;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;74;add_hpx_compile_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;82;add_test_and_deps_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/actions/CMakeLists.txt;51;add_hpx_unit_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/actions/CMakeLists.txt;0;")
add_test(tests.unit.modules.async_distributed.fail_compile_non_const_pointer_argument "/opt/homebrew/bin/cmake" "--build" "/Users/harith/Desktop/Open Source/hpx/build2" "--target" "tests_unit_modules_async_distributed_fail_compile_non_const_pointer_argument" "--config" "Release")
set_tests_properties(tests.unit.modules.async_distributed.fail_compile_non_const_pointer_argument PROPERTIES  RUN_SERIAL "TRUE" WILL_FAIL "TRUE" WORKING_DIRECTORY "/Users/harith/Desktop/Open Source/hpx/build2" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;48;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;74;add_hpx_compile_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;82;add_test_and_deps_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/actions/CMakeLists.txt;51;add_hpx_unit_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/actions/CMakeLists.txt;0;")
add_test(tests.unit.modules.async_distributed.fail_compile_const_pointer_argument "/opt/homebrew/bin/cmake" "--build" "/Users/harith/Desktop/Open Source/hpx/build2" "--target" "tests_unit_modules_async_distributed_fail_compile_const_pointer_argument" "--config" "Release")
set_tests_properties(tests.unit.modules.async_distributed.fail_compile_const_pointer_argument PROPERTIES  RUN_SERIAL "TRUE" WILL_FAIL "TRUE" WORKING_DIRECTORY "/Users/harith/Desktop/Open Source/hpx/build2" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;48;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;74;add_hpx_compile_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;82;add_test_and_deps_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/actions/CMakeLists.txt;51;add_hpx_unit_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/actions/CMakeLists.txt;0;")
add_test(tests.unit.modules.async_distributed.fail_compile_non_const_ref_argument "/opt/homebrew/bin/cmake" "--build" "/Users/harith/Desktop/Open Source/hpx/build2" "--target" "tests_unit_modules_async_distributed_fail_compile_non_const_ref_argument" "--config" "Release")
set_tests_properties(tests.unit.modules.async_distributed.fail_compile_non_const_ref_argument PROPERTIES  RUN_SERIAL "TRUE" WILL_FAIL "TRUE" WORKING_DIRECTORY "/Users/harith/Desktop/Open Source/hpx/build2" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;48;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;74;add_hpx_compile_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddCompileTest.cmake;82;add_test_and_deps_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/actions/CMakeLists.txt;51;add_hpx_unit_compile_test;/Users/harith/Desktop/Open Source/hpx/libs/full/async_distributed/tests/unit/actions/CMakeLists.txt;0;")
