# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/full/parcelset/tests/regressions
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/full/parcelset/tests/regressions
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.regressions.modules.parcelset.distributed.tcp.nested_vectors_6623 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/nested_vectors_6623_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--" "--hpx:ini=hpx.parcel.tcp.max_message_size=0")
set_tests_properties(tests.regressions.modules.parcelset.distributed.tcp.nested_vectors_6623 PROPERTIES  RUN_SERIAL "TRUE" TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/parcelset/tests/regressions/CMakeLists.txt;28;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/parcelset/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.parcelset.distributed.tcp.very_big_parcel "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/very_big_parcel_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--" "--hpx:ini=hpx.parcel.tcp.max_message_size=0")
set_tests_properties(tests.regressions.modules.parcelset.distributed.tcp.very_big_parcel PROPERTIES  RUN_SERIAL "TRUE" TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/parcelset/tests/regressions/CMakeLists.txt;28;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/parcelset/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.parcelset.distributed.tcp.very_big_tchunk "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/very_big_tchunk_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--" "--hpx:ini=hpx.parcel.tcp.max_message_size=0")
set_tests_properties(tests.regressions.modules.parcelset.distributed.tcp.very_big_tchunk PROPERTIES  RUN_SERIAL "TRUE" TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/parcelset/tests/regressions/CMakeLists.txt;28;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/parcelset/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.parcelset.distributed.tcp.very_big_parcel_int_max_plus_1 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/very_big_parcel_test" "-e" "0" "-t" "1" "-l" "2" "-p" "tcp" "-v" "--" "PSEUDO_DEPS_NAME" "very_big_parcel" "--hpx:ini=hpx.parcel.tcp.max_message_size=0" "--nbytes-add=1")
set_tests_properties(tests.regressions.modules.parcelset.distributed.tcp.very_big_parcel_int_max_plus_1 PROPERTIES  RUN_SERIAL "TRUE" TIMEOUT "900" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;227;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/full/parcelset/tests/regressions/CMakeLists.txt;36;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/full/parcelset/tests/regressions/CMakeLists.txt;0;")
