//  Copyright (c) 2019-2025 STE||AR Group
//
//  SPDX-License-Identifier: BSL-1.0
//  Distributed under the Boost Software License, Version 1.0. (See accompanying
//  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

// Do not edit this file! It has been generated by the cmake configuration step.

#pragma once

#include <hpx/config.hpp>

#if defined(HPX_HAVE_MODULE_FUNCTIONAL)
#include <hpx/functional/deferred_call.hpp>
#include <hpx/functional/bind.hpp>
#include <hpx/functional/bind_back.hpp>
#include <hpx/functional/bind_front.hpp>
#include <hpx/functional/first_argument.hpp>
#include <hpx/functional/function.hpp>
#include <hpx/functional/function_ref.hpp>
#include <hpx/functional/invoke.hpp>
#include <hpx/functional/invoke_fused.hpp>
#include <hpx/functional/mem_fn.hpp>
#include <hpx/functional/move_only_function.hpp>
#include <hpx/functional/one_shot.hpp>
#include <hpx/functional/protect.hpp>
#include <hpx/functional/experimental/scope_exit.hpp>
#include <hpx/functional/experimental/scope_fail.hpp>
#include <hpx/functional/experimental/scope_success.hpp>
#include <hpx/functional/reference_wrapper.hpp>
#include <hpx/functional/serialization/reference_wrapper.hpp>
#include <hpx/functional/serialization/serializable_function.hpp>
#include <hpx/functional/serialization/serializable_move_only_function.hpp>
#include <hpx/functional/traits/get_action_name.hpp>
#endif

