# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/examples
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/resource_partitioner/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.examples.modules.resource_partitioner.simplest_resource_partitioner_1 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/simplest_resource_partitioner_1" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.modules.resource_partitioner.simplest_resource_partitioner_1 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/examples/CMakeLists.txt;68;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/examples/CMakeLists.txt;0;")
add_test(tests.examples.modules.resource_partitioner.simplest_resource_partitioner_2 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/simplest_resource_partitioner_2" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.modules.resource_partitioner.simplest_resource_partitioner_2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/examples/CMakeLists.txt;68;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/examples/CMakeLists.txt;0;")
add_test(tests.examples.modules.resource_partitioner.oversubscribing_resource_partitioner "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/oversubscribing_resource_partitioner" "-e" "0" "-t" "4" "-l" "1" "-v" "--" "--use-pools" "--pool-threads" "1")
set_tests_properties(tests.examples.modules.resource_partitioner.oversubscribing_resource_partitioner PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/examples/CMakeLists.txt;68;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/examples/CMakeLists.txt;0;")
add_test(tests.examples.modules.resource_partitioner.simple_resource_partitioner "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/simple_resource_partitioner" "-e" "0" "-t" "4" "-l" "1" "-v" "--" "--use-pools" "--pool-threads" "1")
set_tests_properties(tests.examples.modules.resource_partitioner.simple_resource_partitioner PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/examples/CMakeLists.txt;68;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/examples/CMakeLists.txt;0;")
add_test(tests.examples.modules.resource_partitioner.guided_pool_test "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/guided_pool_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.modules.resource_partitioner.guided_pool_test PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/examples/CMakeLists.txt;68;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/examples/CMakeLists.txt;0;")
add_test(tests.examples.modules.resource_partitioner.async_customization "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/async_customization" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.examples.modules.resource_partitioner.async_customization PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;292;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/examples/CMakeLists.txt;68;add_hpx_example_test;/Users/harith/Desktop/Open Source/hpx/libs/core/resource_partitioner/examples/CMakeLists.txt;0;")
