# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/unit/polymorphic
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/serialization/tests/unit/polymorphic
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.unit.modules.serialization.polymorphic_reference "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/polymorphic_reference_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.serialization.polymorphic_reference PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/unit/polymorphic/CMakeLists.txt;32;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/unit/polymorphic/CMakeLists.txt;0;")
add_test(tests.unit.modules.serialization.polymorphic_pointer "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/polymorphic_pointer_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.serialization.polymorphic_pointer PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/unit/polymorphic/CMakeLists.txt;32;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/unit/polymorphic/CMakeLists.txt;0;")
add_test(tests.unit.modules.serialization.polymorphic_nonintrusive "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/polymorphic_nonintrusive_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.serialization.polymorphic_nonintrusive PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/unit/polymorphic/CMakeLists.txt;32;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/unit/polymorphic/CMakeLists.txt;0;")
add_test(tests.unit.modules.serialization.polymorphic_nonintrusive_abstract "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/polymorphic_nonintrusive_abstract_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.serialization.polymorphic_nonintrusive_abstract PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/unit/polymorphic/CMakeLists.txt;32;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/unit/polymorphic/CMakeLists.txt;0;")
add_test(tests.unit.modules.serialization.polymorphic_semiintrusive_template "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/polymorphic_semiintrusive_template_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.serialization.polymorphic_semiintrusive_template PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/unit/polymorphic/CMakeLists.txt;32;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/unit/polymorphic/CMakeLists.txt;0;")
add_test(tests.unit.modules.serialization.polymorphic_template "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/polymorphic_template_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.serialization.polymorphic_template PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/unit/polymorphic/CMakeLists.txt;32;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/unit/polymorphic/CMakeLists.txt;0;")
add_test(tests.unit.modules.serialization.smart_ptr_polymorphic "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/smart_ptr_polymorphic_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.serialization.smart_ptr_polymorphic PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/unit/polymorphic/CMakeLists.txt;32;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/unit/polymorphic/CMakeLists.txt;0;")
add_test(tests.unit.modules.serialization.smart_ptr_polymorphic_nonintrusive "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/smart_ptr_polymorphic_nonintrusive_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.serialization.smart_ptr_polymorphic_nonintrusive PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/unit/polymorphic/CMakeLists.txt;32;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/serialization/tests/unit/polymorphic/CMakeLists.txt;0;")
