//  Copyright (c) 2020-2025 STE||AR Group
//  Copyright (c) 2017-2022 Hartmut Kaiser
//
//  SPDX-License-Identifier: BSL-1.0
//  Distributed under the Boost Software License, Version 1.0. (See accompanying
//  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

// Do not edit this file! It has been generated by the cmake configuration step.

#include <hpx/modules/config_registry.hpp>

namespace hpx::datastructures_cfg {

    config_registry::add_module_config_helper add_config{
    {
        "datastructures",
        {
            "HPX_DATASTRUCTURES_WITH_ADAPT_STD_TUPLE=ON",
            "HPX_DATASTRUCTURES_WITH_ADAPT_STD_VARIANT=OFF",
        }
    }};
}
