# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/pack_traversal/tests/unit
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/pack_traversal/tests/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.unit.modules.pack_traversal.pack_traversal "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/pack_traversal_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.pack_traversal.pack_traversal PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/pack_traversal/tests/unit/CMakeLists.txt;21;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/pack_traversal/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.pack_traversal.pack_traversal_async "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/pack_traversal_async_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.pack_traversal.pack_traversal_async PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/pack_traversal/tests/unit/CMakeLists.txt;21;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/pack_traversal/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.pack_traversal.unwrap "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/unwrap_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.pack_traversal.unwrap PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/pack_traversal/tests/unit/CMakeLists.txt;21;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/pack_traversal/tests/unit/CMakeLists.txt;0;")
