# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/lcos_local/tests/unit
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/lcos_local/tests/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.unit.modules.lcos_local.channel_local "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/channel_local_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.lcos_local.channel_local PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/lcos_local/tests/unit/CMakeLists.txt;42;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/lcos_local/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.lcos_local.local_dataflow "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/local_dataflow_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.lcos_local.local_dataflow PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/lcos_local/tests/unit/CMakeLists.txt;42;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/lcos_local/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.lcos_local.local_dataflow_small_vector "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/local_dataflow_small_vector_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.lcos_local.local_dataflow_small_vector PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/lcos_local/tests/unit/CMakeLists.txt;42;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/lcos_local/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.lcos_local.local_dataflow_executor "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/local_dataflow_executor_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.lcos_local.local_dataflow_executor PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/lcos_local/tests/unit/CMakeLists.txt;42;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/lcos_local/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.lcos_local.local_dataflow_external_future "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/local_dataflow_external_future_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.lcos_local.local_dataflow_external_future PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/lcos_local/tests/unit/CMakeLists.txt;42;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/lcos_local/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.lcos_local.local_dataflow_executor_additional_arguments "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/local_dataflow_executor_additional_arguments_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.lcos_local.local_dataflow_executor_additional_arguments PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/lcos_local/tests/unit/CMakeLists.txt;42;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/lcos_local/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.lcos_local.local_dataflow_std_array "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/local_dataflow_std_array_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.lcos_local.local_dataflow_std_array PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/lcos_local/tests/unit/CMakeLists.txt;42;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/lcos_local/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.lcos_local.run_guarded "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/run_guarded_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.lcos_local.run_guarded PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/lcos_local/tests/unit/CMakeLists.txt;42;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/lcos_local/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.lcos_local.split_future "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/split_future_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.lcos_local.split_future PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/lcos_local/tests/unit/CMakeLists.txt;42;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/lcos_local/tests/unit/CMakeLists.txt;0;")
