//  Copyright (c) 2019-2025 STE||AR Group
//
//  SPDX-License-Identifier: BSL-1.0
//  Distributed under the Boost Software License, Version 1.0. (See accompanying
//  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

// Do not edit this file! It has been generated by the cmake configuration step.

#pragma once

#include <hpx/config.hpp>

#if defined(HPX_HAVE_MODULE_ASYNC_LOCAL)
#include <hpx/async_local/async.hpp>
#include <hpx/async_local/async_fwd.hpp>
#include <hpx/async_local/dataflow.hpp>
#include <hpx/async_local/post.hpp>
#include <hpx/async_local/sync.hpp>
#include <hpx/async_local/sync_fwd.hpp>
#endif

