# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/execution/tests/regressions
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/execution/tests/regressions
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.regressions.modules.execution.annotated_minmax_2593 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/annotated_minmax_2593_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.execution.annotated_minmax_2593 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/execution/tests/regressions/CMakeLists.txt;31;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/execution/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.execution.chunk_size_4118 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/chunk_size_4118_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.execution.chunk_size_4118 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/execution/tests/regressions/CMakeLists.txt;31;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/execution/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.execution.is_executor_1691 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/is_executor_1691_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.execution.is_executor_1691 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/execution/tests/regressions/CMakeLists.txt;31;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/execution/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.execution.fibonacci_sr "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/fibonacci_sr_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.execution.fibonacci_sr PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/execution/tests/regressions/CMakeLists.txt;31;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/execution/tests/regressions/CMakeLists.txt;0;")
