# Copyright (c)      2017 Thomas Heller
# Copyright (c)      2023 Christopher Taylor
#
# SPDX-License-Identifier: BSL-1.0
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
macro(find_gasnet)

find_package(PkgConfig REQUIRED QUIET COMPONENTS)

if(HPX_WITH_PARCELPORT_GASNET_CONDUIT AND ${HPX_WITH_PARCELPORT_GASNET_CONDUIT} STREQUAL "mpi")
   message(STATUS "GASNet needs to be compiled with the following environment variables set during autoconf: `CFLAGS=-fPIC CXXFLAGS=-fPIC ./configure ...`")
   pkg_search_module(GASNET REQUIRED IMPORTED_TARGET GLOBAL gasnet-mpi-par)
   set(GASNET_MPI_FOUND TRUE)
   hpx_setup_mpi()
else()
   message(STATUS "GASNet needs to be compiled with the following environment variables set during autoconf: `CFLAGS=-fPIC CXXFLAGS=-fPIC ./configure ...`")
   pkg_search_module(GASNET REQUIRED IMPORTED_TARGET GLOBAL gasnet-${HPX_WITH_PARCELPORT_GASNET_CONDUIT}-par)
endif()

target_link_directories(hpx_core PUBLIC ${GASNET_LIBRARY_DIRS})

if(GASNET_CFLAGS)
   set(IS_PARAM "0")
   set(PARAM_FOUND "0")
   set(NEWPARAM "")
   set(IDX 0)
   set(FLAG_LIST "")

   foreach(X IN ITEMS ${GASNET_CFLAGS})
      string(FIND "${X}" "--param" PARAM_FOUND)
      if(NOT "${PARAM_FOUND}" EQUAL "-1")
         set(IS_PARAM "1")
	 set(NEWPARAM "SHELL:${X}")
      endif()
      if("${PARAM_FOUND}" EQUAL "-1" AND "${IS_PARAM}" EQUAL "0" OR "${IS_PARAM}" EQUAL "-1")
	 list(APPEND FLAG_LIST "${X}")
         set(IS_PARAM "0")
      elseif("${PARAM_FOUND}" EQUAL "-1" AND "${IS_PARAM}" EQUAL "1")
	 list(APPEND FLAG_LIST "${NEWPARAM} ${X}")
	 set(NEWPARAM "")
         set(IS_PARAM "0")
      endif()
   endforeach()

   list(LENGTH GASNET_CFLAGS IDX)
   foreach(X RANGE ${IDX})
      list(POP_FRONT GASNET_CFLAGS NEWPARAM)
   endforeach()

   foreach(X IN ITEMS ${FLAG_LIST})
      list(APPEND GASNET_CFLAGS "${X}")
   endforeach()
endif()

if(GASNET_CFLAGS_OTHER)
   set(IS_PARAM "0")
   set(PARAM_FOUND "0")
   set(NEWPARAM "")
   set(IDX 0)
   set(FLAG_LIST "")

   foreach(X IN ITEMS ${GASNET_CFLAGS_OTHER})
      string(FIND "${X}" "--param" PARAM_FOUND)
      if(NOT "${PARAM_FOUND}" EQUAL "-1")
         set(IS_PARAM "1")
	 set(NEWPARAM "SHELL:${X}")
      endif()
      if("${PARAM_FOUND}" EQUAL "-1" AND "${IS_PARAM}" EQUAL "0" OR "${IS_PARAM}" EQUAL "-1")
	 list(APPEND FLAG_LIST "${X}")
         set(IS_PARAM "0")
      elseif("${PARAM_FOUND}" EQUAL "-1" AND "${IS_PARAM}" EQUAL "1")
	 list(APPEND FLAG_LIST "${NEWPARAM} ${X}")
	 set(NEWPARAM "")
         set(IS_PARAM "0")
      endif()
   endforeach()

   list(LENGTH GASNET_CFLAGS_OTHER IDX)
   foreach(X RANGE ${IDX})
      list(POP_FRONT GASNET_CFLAGS_OTHER NEWPARAM)
   endforeach()

   foreach(X IN ITEMS ${FLAG_LIST})
      list(APPEND GASNET_CFLAGS_OTHER "${X}")
   endforeach()
endif()

if(GASNET_LDFLAGS)
   set(IS_PARAM "0")
   set(PARAM_FOUND "0")
   set(NEWPARAM "")
   set(IDX 0)
   set(DIRIDX 0)
   set(FLAG_LIST "")
   set(DIR_LIST "")
   set(LIB_LIST "")

   foreach(X IN ITEMS ${GASNET_LDFLAGS})
      string(FIND "${X}" "--param" PARAM_FOUND)
      string(FIND "${X}" "-lgasnet" IDX)
      string(FIND "${X}" "-l" LIDX)
      string(FIND "${X}" "-L" DIRIDX)
      if(NOT "${PARAM_FOUND}" EQUAL "-1")
         set(IS_PARAM "1")
	 set(NEWPARAM "SHELL:${X}")
      endif()
      if("${PARAM_FOUND}" EQUAL "-1" AND "${IDX}" EQUAL "-1" AND "${IS_PARAM}" EQUAL "0" OR "${IS_PARAM}" EQUAL "-1")
	 list(APPEND FLAG_LIST "${X}")
         set(IS_PARAM "0")
      elseif("${PARAM_FOUND}" EQUAL "-1" AND "${IS_PARAM}" EQUAL "1")
	 list(APPEND FLAG_LIST "${NEWPARAM} ${X}")
	 set(NEWPARAM "")
         set(IS_PARAM "0")
      elseif(NOT "${IDX}" EQUAL "-1" AND NOT "${LIDX}" EQUAL "-1")
	 set(TMPSTR "")
	 string(REPLACE "-l" "" TMPSTR "${X}")
	 list(APPEND LIB_LIST "${TMPSTR}")
         set(IDX 0)
      elseif("${IDX}" EQUAL "-1" AND NOT "${LIDX}" EQUAL "-1")
	 list(APPEND FLAG_LIST "${X}")
      endif()
      if(NOT "${DIRIDX}" EQUAL "-1")
	 set(TMPSTR "")
	 string(REPLACE "-L" "" TMPSTR "${X}")
	 list(APPEND DIR_LIST "${TMPSTR}")
      endif()
   endforeach()

   set(IDX 0)
   list(LENGTH GASNET_LDFLAGS IDX)
   foreach(X RANGE ${IDX})
      list(POP_FRONT GASNET_LDFLAGS NEWPARAM)
   endforeach()

   foreach(X IN ITEMS ${FLAG_LIST})
      list(APPEND GASNET_LDFLAGS "${X}")
   endforeach()

   set(IDX 0)
   list(LENGTH LIB_LIST IDX)
   if(NOT "${IDX}" EQUAL "0")
      set(IDX 0)
      set(NEWLINK "SHELL:-Wl,--whole-archive ")
      foreach(X IN ITEMS ${LIB_LIST})
	 set(DIRSTR "")
	 string(REPLACE ";" " " DIRSTR "${DIR_LIST}")
	 foreach(Y IN ITEMS ${DIR_LIST})
  	    find_library(FOUND_LIB
	       NAMES ${X} "lib${X}" "lib${X}.a"
	       PATHS ${Y}
    	       HINTS ${Y}
	       NO_CACHE
	       NO_CMAKE_FIND_ROOT_PATH
	       NO_DEFAULT_PATH)

            list(LENGTH FOUND_LIB IDX)
   	    if(NOT "${IDX}" EQUAL "0")
	       string(APPEND NEWLINK "${FOUND_LIB}")
	       set(FOUND_LIB "")
	    endif()
         endforeach()
      endforeach()
      string(APPEND NEWLINK " -Wl,--no-whole-archive")
      string(FIND "SHELL:-Wl,--whole-archive  -Wl,--no-whole-archive" "${NEWLINK}" IDX)
      if("${IDX}" EQUAL "-1")
         list(APPEND GASNET_LDFLAGS "${NEWLINK}")
      endif()
   endif()
endif()

if(GASNET_LDFLAGS_OTHER)
   unset(FOUND_LIB)
   set(IS_PARAM "0")
   set(PARAM_FOUND "0")
   set(NEWPARAM "")
   set(IDX 0)
   set(DIRIDX 0)
   set(FLAG_LIST "")
   set(DIR_LIST "")
   set(LIB_LIST "")

   foreach(X IN ITEMS ${GASNET_LDFLAGS_OTHER})
      string(FIND "${X}" "--param" PARAM_FOUND)
      string(FIND "${X}" "-lgasnet" IDX)
      string(FIND "${X}" "-L" DIRIDX)
      if(NOT "${PARAM_FOUND}" EQUAL "-1")
         set(IS_PARAM "1")
	 set(NEWPARAM "SHELL:${X}")
      endif()
      if("${PARAM_FOUND}" EQUAL "-1" AND "${IDX}" EQUAL "-1" AND "${IS_PARAM}" EQUAL "0" OR "${IS_PARAM}" EQUAL "-1")
	 list(APPEND FLAG_LIST "${X}")
         set(IS_PARAM "0")
      elseif("${PARAM_FOUND}" EQUAL "-1" AND "${IS_PARAM}" EQUAL "1")
	 list(APPEND FLAG_LIST "${NEWPARAM} ${X}")
	 set(NEWPARAM "")
         set(IS_PARAM "0")
      elseif(NOT "${IDX}" EQUAL "-1" AND NOT "${LIDX}" EQUAL "-1")
	 set(TMPSTR "")
	 string(REPLACE "-l" "" TMPSTR "${X}")
	 list(APPEND LIB_LIST "${TMPSTR}")
         set(IDX 0)
      elseif("${IDX}" EQUAL "-1" AND NOT "${LIDX}" EQUAL "-1")
	 list(APPEND FLAG_LIST "${X}")
      endif()
      if(NOT "${DIRIDX}" EQUAL "-1")
	 set(TMPSTR "")
	 string(REPLACE "-L" "" TMPSTR "${X}")
	 list(APPEND DIR_LIST "${TMPSTR}")
      endif()
   endforeach()

   set(IDX 0)
   list(LENGTH GASNET_LDFLAGS_OTHER IDX)
   foreach(X RANGE ${IDX})
      list(POP_FRONT GASNET_LDFLAGS_OTHER NEWPARAM)
   endforeach()

   foreach(X IN ITEMS ${FLAG_LIST})
       list(APPEND GASNET_LDFLAGS_OTHER "${X}")
   endforeach()

   set(IDX 0)
   list(LENGTH LIB_LIST IDX)
   if(NOT "${IDX}" EQUAL "0")
      set(IDX 0)
      set(NEWLINK "SHELL:-Wl,--whole-archive ")
      foreach(X IN ITEMS ${LIB_LIST})
	 set(DIRSTR "")
	 string(REPLACE ";" " " DIRSTR "${DIR_LIST}")
	 foreach(Y IN ITEMS ${DIR_LIST})
  	    find_library(FOUND_LIB
	       NAMES ${X} "lib${X}" "lib${X}.a"
	       PATHS ${Y}
    	       HINTS ${Y}
	       NO_CACHE
	       NO_CMAKE_FIND_ROOT_PATH
	       NO_DEFAULT_PATH)

            list(LENGTH FOUND_LIB IDX)
   	    if(NOT "${IDX}" EQUAL "0")
   	       string(APPEND NEWLINK "${FOUND_LIB}")
	       set(FOUND_LIB "")
	    endif()
         endforeach()
      endforeach()
      string(APPEND NEWLINK " -Wl,--no-whole-archive")

      string(FIND "SHELL:-Wl,--whole-archive  -Wl,--no-whole-archive" "${NEWLINK}" IDX)
      if("${IDX}" EQUAL "-1")
	      list(APPEND GASNET_LDFLAGS_OTHER "${NEWLINK}")
      endif()
   endif()

endif()

if(GASNET_STATIC_CFLAGS)
   set(IS_PARAM "0")
   set(PARAM_FOUND "0")
   set(NEWPARAM "")
   set(IDX 0)
   set(FLAG_LIST "")

   foreach(X IN ITEMS ${GASNET_STATIC_CFLAGS})
      string(FIND "${X}" "--param" PARAM_FOUND)
      if(NOT "${PARAM_FOUND}" EQUAL "-1")
         set(IS_PARAM "1")
	 set(NEWPARAM "SHELL:${X}")
      endif()
      if("${PARAM_FOUND}" EQUAL "-1" AND "${IS_PARAM}" EQUAL "0" OR "${IS_PARAM}" EQUAL "-1")
	 list(APPEND FLAG_LIST "${X}")
         set(IS_PARAM "0")
      elseif("${PARAM_FOUND}" EQUAL "-1" AND "${IS_PARAM}" EQUAL "1")
	 list(APPEND FLAG_LIST "${NEWPARAM} ${X}")
	 set(NEWPARAM "")
         set(IS_PARAM "0")
      endif()
   endforeach()

   list(LENGTH GASNET_STATIC_CFLAGS IDX)
   foreach(X RANGE ${IDX})
      list(POP_FRONT GASNET_STATIC_CFLAGS NEWPARAM)
   endforeach()

   foreach(X IN ITEMS ${FLAG_LIST})
      list(APPEND GASNET_STATIC_CFLAGS "${X}")
   endforeach()
endif()

if(GASNET_STATIC_CFLAGS_OTHER)
   set(IS_PARAM "0")
   set(PARAM_FOUND "0")
   set(NEWPARAM "")
   set(IDX 0)
   set(FLAG_LIST "")

   foreach(X IN ITEMS ${GASNET_STATIC_CFLAGS_OTHER})
      string(FIND "${X}" "--param" PARAM_FOUND)
      if(NOT "${PARAM_FOUND}" EQUAL "-1")
         set(IS_PARAM "1")
	 set(NEWPARAM "SHELL:${X}")
      endif()
      if("${PARAM_FOUND}" EQUAL "-1" AND "${IS_PARAM}" EQUAL "0" OR "${IS_PARAM}" EQUAL "-1")
	 list(APPEND FLAG_LIST "${X}")
         set(IS_PARAM "0")
      elseif("${PARAM_FOUND}" EQUAL "-1" AND "${IS_PARAM}" EQUAL "1")
	 list(APPEND FLAG_LIST "${NEWPARAM} ${X}")
	 set(NEWPARAM "")
         set(IS_PARAM "0")
      endif()
   endforeach()

   list(LENGTH GASNET_STATIC_CFLAGS_OTHER IDX)
   foreach(X RANGE ${IDX})
      list(POP_FRONT GASNET_STATIC_CFLAGS_OTHER NEWPARAM)
   endforeach()

   foreach(X IN ITEMS ${FLAG_LIST})
      list(APPEND GASNET_STATIC_CFLAGS_OTHER "${X}")
   endforeach()
endif()

if(GASNET_STATIC_LDFLAGS)
   unset(FOUND_LIB)
   set(IS_PARAM "0")
   set(PARAM_FOUND "0")
   set(NEWPARAM "")
   set(IDX 0)
   set(DIRIDX 0)
   set(FLAG_LIST "")
   set(DIR_LIST "")
   set(LIB_LIST "")

   foreach(X IN ITEMS ${GASNET_STATIC_LDFLAGS})
      string(FIND "${X}" "--param" PARAM_FOUND)
      string(FIND "${X}" "-lgasnet" IDX)
      string(FIND "${X}" "-L" DIRIDX)
      if(NOT "${PARAM_FOUND}" EQUAL "-1")
         set(IS_PARAM "1")
	 set(NEWPARAM "SHELL:${X}")
      endif()
      if("${PARAM_FOUND}" EQUAL "-1" AND "${IDX}" EQUAL "-1" AND "${IS_PARAM}" EQUAL "0" OR "${IS_PARAM}" EQUAL "-1")
	 list(APPEND FLAG_LIST "${X}")
         set(IS_PARAM "0")
      elseif("${PARAM_FOUND}" EQUAL "-1" AND "${IS_PARAM}" EQUAL "1")
	 list(APPEND FLAG_LIST "${NEWPARAM} ${X}")
	 set(NEWPARAM "")
         set(IS_PARAM "0")
      elseif(NOT "${IDX}" EQUAL "-1" AND NOT "${LIDX}" EQUAL "-1")
	 set(TMPSTR "")
	 string(REPLACE "-l" "" TMPSTR "${X}")
	 list(APPEND LIB_LIST "${TMPSTR}")
         set(IDX 0)
      elseif("${IDX}" EQUAL "-1" AND NOT "${LIDX}" EQUAL "-1")
	 list(APPEND FLAG_LIST "${X}")
      endif()
      if(NOT "${DIRIDX}" EQUAL "-1")
	 set(TMPSTR "")
	 string(REPLACE "-L" "" TMPSTR "${X}")
	 list(APPEND DIR_LIST "${TMPSTR}")
      endif()
   endforeach()

   set(IDX 0)
   list(LENGTH GASNET_STATIC_LDFLAGS IDX)
   foreach(X RANGE ${IDX})
      list(POP_FRONT GASNET_STATIC_LDFLAGS NEWPARAM)
   endforeach()

   foreach(X IN ITEMS ${FLAG_LIST})
      list(APPEND GASNET_STATIC_LDFLAGS "${X}")
   endforeach()

   set(IDX 0)
   list(LENGTH LIB_LIST IDX)
   if(NOT "${IDX}" EQUAL "0")
      set(IDX 0)
      set(NEWLINK "SHELL:-Wl,--whole-archive ")
      foreach(X IN ITEMS ${LIB_LIST})
	 set(DIRSTR "")
	 string(REPLACE ";" " " DIRSTR "${DIR_LIST}")
	 foreach(Y IN ITEMS ${DIR_LIST})
	 find_library(FOUND_LIB
	       NAMES ${X} "lib${X}" "lib${X}.a"
	       PATHS ${Y}
    	       HINTS ${Y}
	       NO_CACHE
	       NO_CMAKE_FIND_ROOT_PATH
	       NO_DEFAULT_PATH)

            list(LENGTH FOUND_LIB IDX)

   	    if(NOT "${IDX}" EQUAL "0")
	       string(APPEND NEWLINK "${FOUND_LIB}")
	       set(FOUND_LIB "")
	    endif()
         endforeach()
      endforeach()
      string(APPEND NEWLINK " -Wl,--no-whole-archive")

      string(FIND "SHELL:-Wl,--whole-archive  -Wl,--no-whole-archive" "${NEWLINK}" IDX)
      if("${IDX}" EQUAL "-1")
	      list(APPEND GASNET_STATIC_LDFLAGS "${NEWLINK}")
      endif()
   endif()
endif()

if(GASNET_STATIC_LDFLAGS_OTHER)
   unset(FOUND_LIB)
   set(IS_PARAM "0")
   set(PARAM_FOUND "0")
   set(NEWPARAM "")
   set(IDX 0)
   set(DIRIDX 0)
   set(FLAG_LIST "")
   set(DIR_LIST "")
   set(LIB_LIST "")

   foreach(X IN ITEMS ${GASNET_STATIC_LDFLAGS_OTHER})
      string(FIND "${X}" "--param" PARAM_FOUND)
      string(FIND "${X}" "-lgasnet" IDX)
      string(FIND "${X}" "-L" DIRIDX)
      if(NOT "${PARAM_FOUND}" EQUAL "-1")
         set(IS_PARAM "1")
	 set(NEWPARAM "SHELL:${X}")
      endif()
      if("${PARAM_FOUND}" EQUAL "-1" AND "${IDX}" EQUAL "-1" AND "${IS_PARAM}" EQUAL "0" OR "${IS_PARAM}" EQUAL "-1")
	 list(APPEND FLAG_LIST "${X}")
         set(IS_PARAM "0")
      elseif("${PARAM_FOUND}" EQUAL "-1" AND "${IS_PARAM}" EQUAL "1")
	 list(APPEND FLAG_LIST "${NEWPARAM} ${X}")
	 set(NEWPARAM "")
         set(IS_PARAM "0")
      elseif(NOT "${IDX}" EQUAL "-1" AND NOT "${LIDX}" EQUAL "-1")
	 set(TMPSTR "")
	 string(REPLACE "-l" "" TMPSTR "${X}")
	 list(APPEND LIB_LIST "${TMPSTR}")
         set(IDX 0)
      elseif("${IDX}" EQUAL "-1" AND NOT "${LIDX}" EQUAL "-1")
	 list(APPEND FLAG_LIST "${X}")
      endif()
      if(NOT "${DIRIDX}" EQUAL "-1")
	 set(TMPSTR "")
	 string(REPLACE "-L" "" TMPSTR "${X}")
	 list(APPEND DIR_LIST "${TMPSTR}")
      endif()
   endforeach()

   set(IDX 0)
   list(LENGTH GASNET_STATIC_LDFLAGS_OTHER IDX)
   foreach(X RANGE ${IDX})
       list(POP_FRONT GASNET_STATIC_LDFLAGS_OTHER NEWPARAM)
   endforeach()

   foreach(X IN ITEMS ${FLAG_LIST})
       list(APPEND GASNET_STATIC_LDFLAGS_OTHER "${X}")
   endforeach()

   set(IDX 0)
   list(LENGTH LIB_LIST IDX)
   if(NOT "${IDX}" EQUAL "0")
      set(IDX 0)
      set(NEWLINK "SHELL:-Wl,--whole-archive ")
      foreach(X IN ITEMS ${LIB_LIST})
	 set(DIRSTR "")
	 string(REPLACE ";" " " DIRSTR "${DIR_LIST}")
	 foreach(Y IN ITEMS ${DIR_LIST})
  	    find_library(FOUND_LIB
	       NAMES ${X} "lib${X}" "lib${X}.a"
	       PATHS ${Y}
    	       HINTS ${Y}
	       NO_CACHE
	       NO_CMAKE_FIND_ROOT_PATH
	       NO_DEFAULT_PATH)

            list(LENGTH FOUND_LIB IDX)

	    message(STATUS "${FOUND_LIB} ${X}")
   	    if(NOT "${IDX}" EQUAL "0")
		    string(APPEND NEWLINK "${FOUND_LIB}")
	       set(FOUND_LIB "")
	    endif()
         endforeach()
      endforeach()
      string(APPEND NEWLINK " -Wl,--no-whole-archive")
      string(FIND "SHELL:-Wl,--whole-archive  -Wl,--no-whole-archive" "${NEWLINK}" IDX)
      if("${IDX}" EQUAL "-1")
	      list(APPEND GASNET_STATIC_LDFLAGS_OTHER "${NEWLINK}")
      endif()
   endif()
endif()

set_target_properties(PkgConfig::GASNET PROPERTIES INTERFACE_COMPILE_OPTIONS "${GASNET_CFLAGS}")
set_target_properties(PkgConfig::GASNET PROPERTIES INTERFACE_LINK_OPTIONS    "${GASNET_LDFLAGS}")

endmacro()
