# Copyright (c) 2011 Bryce Lelbach
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying 
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

source_group(hpx REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/.*hpp")
source_group(hpx/components/distributing_factory REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/components/distributing_factory/.*hpp")
source_group(hpx/components/distributing_factory/server REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/components/distributing_factory/server/.*hpp")
source_group(hpx/components/distributing_factory/stubs REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/components/distributing_factory/stubs/.*hpp")
source_group(hpx/config REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/config/.*hpp")
source_group(hpx/include REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/include/.*hpp")
source_group(hpx/lcos REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/lcos/.*hpp")
source_group(hpx/lcos/server REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/lcos/server/.*hpp")
source_group(hpx/lcos/stubs REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/lcos/stubs/.*hpp")
source_group(hpx/performance_counters REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/performance_counters/.*hpp")
source_group(hpx/performance_counters/server REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/performance_counters/server/.*hpp")
source_group(hpx/performance_counters/stubs REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/performance_counters/stubs/.*hpp")
source_group(hpx/runtime REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/runtime/.*hpp")
source_group(hpx/runtime/actions REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/runtime/actions/.*hpp")
source_group(hpx/runtime/applier REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/runtime/applier/.*hpp")
source_group(hpx/runtime/components REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/runtime/components/.*hpp")
source_group(hpx/runtime/components/server REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/runtime/components/server/.*hpp")
source_group(hpx/runtime/components/stubs REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/runtime/components/stubs/.*hpp")
source_group(hpx/runtime/naming REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/runtime/naming/.*hpp")
source_group(hpx/runtime/naming/detail REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/runtime/naming/detail/.*hpp")
source_group(hpx/runtime/naming/server REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/runtime/naming/server/.*hpp")
source_group(hpx/runtime/parcelset REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/runtime/parcelset/.*hpp")
source_group(hpx/runtime/parcelset/server REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/runtime/parcelset/server/.*hpp")
source_group(hpx/runtime/threads REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/runtime/threads/.*hpp")
source_group(hpx/runtime/threads/detail REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/runtime/threads/detail/.*hpp")
source_group(hpx/runtime/threads/policies REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/runtime/threads/policies/.*hpp")
source_group(hpx/util REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/util/.*hpp")
source_group(hpx/util/hardware REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/hpx/util/hardware/.*hpp")

source_group(hpx REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/.*cpp")
source_group(hpx/components/distributing_factory REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/components/distributing_factory/.*cpp")
source_group(hpx/components/distributing_factory/server REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/components/distributing_factory/server/.*cpp")
source_group(hpx/components/distributing_factory/stubs REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/components/distributing_factory/stubs/.*cpp")
source_group(hpx/config REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/config/.*cpp")
source_group(hpx/include REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/include/.*cpp")
source_group(hpx/lcos REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/lcos/.*cpp")
source_group(hpx/lcos/server REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/lcos/server/.*cpp")
source_group(hpx/lcos/stubs REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/lcos/stubs/.*cpp")
source_group(hpx/performance_counters REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/performance_counters/.*cpp")
source_group(hpx/performance_counters/server REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/performance_counters/server/.*cpp")
source_group(hpx/performance_counters/stubs REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/performance_counters/stubs/.*cpp")
source_group(hpx/runtime REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/runtime/.*cpp")
source_group(hpx/runtime/actions REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/runtime/actions/.*cpp")
source_group(hpx/runtime/applier REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/runtime/applier/.*cpp")
source_group(hpx/runtime/components REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/runtime/components/.*cpp")
source_group(hpx/runtime/components/server REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/runtime/components/server/.*cpp")
source_group(hpx/runtime/components/stubs REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/runtime/components/stubs/.*cpp")
source_group(hpx/runtime/naming REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/runtime/naming/.*cpp")
source_group(hpx/runtime/naming/detail REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/runtime/naming/detail/.*cpp")
source_group(hpx/runtime/naming/server REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/runtime/naming/server/.*cpp")
source_group(hpx/runtime/parcelset REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/runtime/parcelset/.*cpp")
source_group(hpx/runtime/parcelset/server REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/runtime/parcelset/server/.*cpp")
source_group(hpx/runtime/threads REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/runtime/threads/.*cpp")
source_group(hpx/runtime/threads/detail REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/runtime/threads/detail/.*cpp")
source_group(hpx/runtime/threads/policies REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/runtime/threads/policies/.*cpp")
source_group(hpx/util REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/util/.*cpp")
source_group(hpx/util/hardware REGULAR_EXPRESSION "${hpx_SOURCE_DIR}/src/util/hardware/.*cpp")

