# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/algorithms/detail
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/algorithms/tests/unit/algorithms/detail
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.unit.modules.algorithms.detail.chunk_size_iterator "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/chunk_size_iterator_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.algorithms.detail.chunk_size_iterator PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/algorithms/detail/CMakeLists.txt;34;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/algorithms/detail/CMakeLists.txt;0;")
add_test(tests.unit.modules.algorithms.detail.chunk_size_idx_iterator "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/chunk_size_idx_iterator_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.algorithms.detail.chunk_size_idx_iterator PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/algorithms/detail/CMakeLists.txt;34;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/algorithms/detail/CMakeLists.txt;0;")
add_test(tests.unit.modules.algorithms.detail.test_insertion_sort "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/test_insertion_sort_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.algorithms.detail.test_insertion_sort PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/algorithms/detail/CMakeLists.txt;34;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/algorithms/detail/CMakeLists.txt;0;")
add_test(tests.unit.modules.algorithms.detail.test_parallel_stable_sort "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/test_parallel_stable_sort_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.algorithms.detail.test_parallel_stable_sort PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/algorithms/detail/CMakeLists.txt;34;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/algorithms/detail/CMakeLists.txt;0;")
add_test(tests.unit.modules.algorithms.detail.test_sample_sort "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/test_sample_sort_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.algorithms.detail.test_sample_sort PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/algorithms/detail/CMakeLists.txt;34;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/algorithms/detail/CMakeLists.txt;0;")
add_test(tests.unit.modules.algorithms.detail.test_spin_sort "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/test_spin_sort_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.algorithms.detail.test_spin_sort PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/algorithms/detail/CMakeLists.txt;34;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/algorithms/tests/unit/algorithms/detail/CMakeLists.txt;0;")
