# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/program_options/tests/regressions
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/program_options/tests/regressions
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.regressions.modules.program_options.command_line_arguments_706 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/command_line_arguments_706_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.program_options.command_line_arguments_706 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/tests/regressions/CMakeLists.txt;28;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.program_options.commandline_options_1437 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/commandline_options_1437_test" "-e" "0" "-t" "2" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.program_options.commandline_options_1437 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/tests/regressions/CMakeLists.txt;28;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/tests/regressions/CMakeLists.txt;0;")
add_test(tests.regressions.modules.program_options.command_line_required_arguments_2990 "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/command_line_required_arguments_2990_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.regressions.modules.program_options.command_line_required_arguments_2990 PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;282;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/tests/regressions/CMakeLists.txt;28;add_hpx_regression_test;/Users/harith/Desktop/Open Source/hpx/libs/core/program_options/tests/regressions/CMakeLists.txt;0;")
