# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/compute_local/tests/unit
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/compute_local/tests/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.unit.modules.compute_local.block_allocator "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/block_allocator_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.compute_local.block_allocator PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/compute_local/tests/unit/CMakeLists.txt;37;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/compute_local/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.compute_local.block_fork_join_executor "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/block_fork_join_executor_test" "-e" "0" "-t" "1" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.compute_local.block_fork_join_executor PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/compute_local/tests/unit/CMakeLists.txt;37;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/compute_local/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.compute_local.numa_allocator "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/numa_allocator_test" "-e" "0" "-t" "-2" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.compute_local.numa_allocator PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/compute_local/tests/unit/CMakeLists.txt;37;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/compute_local/tests/unit/CMakeLists.txt;0;")
