# CMake generated Testfile for 
# Source directory: /Users/harith/Desktop/Open Source/hpx/libs/core/timed_execution/tests/unit
# Build directory: /Users/harith/Desktop/Open Source/hpx/build2/libs/core/timed_execution/tests/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests.unit.modules.timed_execution.minimal_timed_async_executor "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/minimal_timed_async_executor_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.timed_execution.minimal_timed_async_executor PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/timed_execution/tests/unit/CMakeLists.txt;28;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/timed_execution/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.timed_execution.minimal_timed_sync_executor "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/minimal_timed_sync_executor_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.timed_execution.minimal_timed_sync_executor PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/timed_execution/tests/unit/CMakeLists.txt;28;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/timed_execution/tests/unit/CMakeLists.txt;0;")
add_test(tests.unit.modules.timed_execution.timed_parallel_executor "/Users/harith/Desktop/Open Source/hpx/build2/bin/hpxrun.py" "/Users/harith/Desktop/Open Source/hpx/build2/bin/timed_parallel_executor_test" "-e" "0" "-t" "4" "-l" "1" "-v" "--")
set_tests_properties(tests.unit.modules.timed_execution.timed_parallel_executor PROPERTIES  _BACKTRACE_TRIPLES "/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;126;add_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;269;add_hpx_test;/Users/harith/Desktop/Open Source/hpx/cmake/HPX_AddTest.cmake;277;add_test_and_deps_test;/Users/harith/Desktop/Open Source/hpx/libs/core/timed_execution/tests/unit/CMakeLists.txt;28;add_hpx_unit_test;/Users/harith/Desktop/Open Source/hpx/libs/core/timed_execution/tests/unit/CMakeLists.txt;0;")
