//  Copyright (c) 2019-2025 STE||AR Group
//
//  SPDX-License-Identifier: BSL-1.0
//  Distributed under the Boost Software License, Version 1.0. (See accompanying
//  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

// Do not edit this file! It has been generated by the cmake configuration step.

#pragma once

#include <hpx/config.hpp>

#if defined(HPX_HAVE_MODULE_COMPUTE)
#include <hpx/compute/host/distributed_target.hpp>
#include <hpx/compute/host/get_targets.hpp>
#include <hpx/compute/host.hpp>
#include <hpx/compute/host/target_distribution_policy.hpp>
#include <hpx/compute/traits.hpp>
#endif

