# Copyright (c) 2026 The STE||AR Group
#
# SPDX-License-Identifier: BSL-1.0
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

name: Build and Test

on:
  pull_request:
  push:
    branches:
      - master
      - 'release**'
  workflow_dispatch:

jobs:
  configure-core-core_local-components:
    runs-on: ubuntu-latest
    container: stellargroup/build_env:17

    steps:
      - uses: actions/checkout@v6

      - name: Configure (Running CMake)
        shell: bash
        timeout-minutes: 30
        run: |
          mkdir -p "$GITHUB_WORKSPACE/build"
          cd "$GITHUB_WORKSPACE/build"

          cmake --version
          if [ "${{ github.event_name }}" != "pull_request" ] && \
            { [ "${{ github.ref_name }}" == "master" ] || \
              [[ "${{ github.ref_name }}" =~ ^release.* ]] || \
              [ "${{ github.ref_type }}" == "tag" ]; }; then
            DOCUMENTATION_OUTPUT_FORMATS="html;singlehtml;latexpdf"
          else
            DOCUMENTATION_OUTPUT_FORMATS="html"
          fi

          # Disable Vc for now as otherwise we need to reconfigure during the
          # install step, which in turn forces everything to be rebuilt.
          # -DHPX_WITH_DATAPAR_VC=On
          cmake \
            "$GITHUB_WORKSPACE" \
            -G "Ninja" \
            -DCMAKE_BUILD_TYPE=Debug \
            -DHPX_WITH_MALLOC=system \
            -DHPX_WITH_FETCH_ASIO=Off \
            -DHPX_WITH_GIT_COMMIT=${{ github.sha }} \
            -DHPX_WITH_GIT_BRANCH="${{ github.ref_name }}" \
            -DHPX_WITH_GIT_TAG="${{ github.ref_type == 'tag' && github.ref_name || '' }}" \
            -DHPX_WITH_TOOLS=On \
            -DCMAKE_CXX_FLAGS="-fcolor-diagnostics" \
            -DHPX_WITH_TESTS_HEADERS=On \
            -DHPX_WITH_COMPILER_WARNINGS=On \
            -DHPX_WITH_COMPILER_WARNINGS_AS_ERRORS=On \
            -DHPX_WITH_DEPRECATION_WARNINGS=On \
            -DCMAKE_CXX_CLANG_TIDY=clang-tidy-20 \
            -DHPX_WITH_THREAD_LOCAL_STORAGE=On \
            -DHPX_WITH_STACKTRACES_STATIC_SYMBOLS=On \
            -DHPX_WITH_STACKTRACES_DEMANGLE_SYMBOLS=Off \
            -DHPX_WITH_TESTS_DEBUG_LOG=On \
            -DHPX_WITH_TESTS_DEBUG_LOG_DESTINATION="$GITHUB_WORKSPACE/build/debug-log.txt" \
            -DHPX_WITH_SPINLOCK_DEADLOCK_DETECTION=On \
            -DHPX_WITH_CHECK_MODULE_DEPENDENCIES=On \
            -DHPX_LOGGING_WITH_SEPARATE_DESTINATIONS=Off \
            -DHPX_WITH_THREAD_DEBUG_INFO=On \
            -DHPX_COMMAND_LINE_HANDLING_WITH_JSON_CONFIGURATION_FILES=On \
            -DHPX_WITH_FETCH_JSON=On \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=On \
            -DHPX_WITH_DOCUMENTATION=On \
            -DHPX_WITH_DOCUMENTATION_OUTPUT_FORMATS="${DOCUMENTATION_OUTPUT_FORMATS}" \
            -DHPX_WITH_TESTS_COMMAND_LINE=--hpx:queuing=local-workrequesting-fifo \
            -DHPX_WITH_TESTS_MAX_THREADS_PER_LOCALITY=2

      - name: core_local (Building Core Local)
        shell: bash
        working-directory: build
        run: ninja -j2 -k 0 hpx_core

      - name: core (Building Core)
        shell: bash
        working-directory: build
        run: ninja -j2 -k 0 core

      - name: Components (Building Components)
        shell: bash
        working-directory: build
        run: ninja -j2 -k 0 components

      - name: Package Build Artifacts
        run: tar -czf build.tar.gz build/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: hpx-build-${{ github.sha }}
          path: build.tar.gz
          retention-days: 3

  build-and-test:
    needs: configure-core-core_local-components
    runs-on: ubuntu-latest
    container: stellargroup/build_env:17
    name: ${{ matrix.job_name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - job_name: tests-example1
            artifact_job_name: tests-example1
            target_file: .github/test-targets/tests.examples1.targets
            build_jobs: "2"
          - job_name: tests-example2
            artifact_job_name: tests-example2
            target_file: .github/test-targets/tests.examples2.targets
            build_jobs: "2"
            ctest_exclude_regex: tests.examples.transpose.transpose_block_numa
          - job_name: tests-unit1-algorithms
            artifact_job_name: tests-unit1-algorithms
            target_file: .github/test-targets/tests.unit1.algorithms
            build_jobs: "1"
          - job_name: tests-unit2-algorithms
            artifact_job_name: tests-unit2-algorithms
            target_file: .github/test-targets/tests.unit2.algorithms
            build_jobs: "1"
          - job_name: tests-unit3-algorithms
            artifact_job_name: tests-unit3-algorithms
            target_file: .github/test-targets/tests.unit3.algorithms
            build_jobs: "1"
            ctest_exclude_regex: tests.unit.modules.algorithms.algorithms.foreach_std_policies
          - job_name: tests-unit4-algorithms
            artifact_job_name: tests-unit4-algorithms
            target_file: .github/test-targets/tests.unit4.algorithms
            build_jobs: "1"
          - job_name: tests-unit1-container_algorithms
            artifact_job_name: tests-unit1-container-algorithms
            target_file: .github/test-targets/tests.unit1.container_algorithms
            build_jobs: "2"
            ctest_exclude_regex: tests.unit.modules.algorithms.container_algorithms.for_loop_range_generator
          - job_name: tests-unit2-container_algorithms
            artifact_job_name: tests-unit2-container-algorithms
            target_file: .github/test-targets/tests.unit2.container_algorithms
            build_jobs: "2"
          - job_name: tests-unit1-segmented_algorithms
            artifact_job_name: tests-unit1-segmented-algorithms
            target_file: .github/test-targets/tests.unit1.segmented_algorithms
            build_jobs: "1"
            ctest_regex_transform: segmented_algorithms
          - job_name: tests-unit2-segmented_algorithms
            artifact_job_name: tests-unit2-segmented-algorithms
            target_file: .github/test-targets/tests.unit2.segmented_algorithms
            build_jobs: "1"
            ctest_regex_transform: segmented_algorithms
          - job_name: tests-unit1
            artifact_job_name: tests-unit1
            target_file: .github/test-targets/tests.unit1.targets
            build_jobs: "2"
          - job_name: tests-unit2
            artifact_job_name: tests-unit2
            target_file: .github/test-targets/tests.unit2.targets
            build_jobs: "2"
            ctest_exclude_regex: tests.unit.modules.compute_local.numa_allocator
          - job_name: tests-unit3
            artifact_job_name: tests-unit3
            target_file: .github/test-targets/tests.unit3.targets
            build_jobs: "2"
          - job_name: tests-unit4
            artifact_job_name: tests-unit4
            target_file: .github/test-targets/tests.unit4.targets
            build_jobs: "2"
            ctest_exclude_regex: tests.unit.modules.resource_partitioner.scheduler_binding_check
          - job_name: tests-unit5
            artifact_job_name: tests-unit5
            target_file: .github/test-targets/tests.unit5.targets
            build_jobs: "2"
          - job_name: tests-regression1
            artifact_job_name: tests-regressions1
            target_file: .github/test-targets/tests.regressions1.targets
            build_jobs: "2"
            ctest_exclude_regex: tests.regressions.modules.threading_base.thread_stacksize_current
          - job_name: tests-regression2
            artifact_job_name: tests-regressions2
            target_file: .github/test-targets/tests.regressions2.targets
            build_jobs: "2"
            ctest_exclude_regex: tests.regressions.modules.command_line_handling_local|tests.regressions.modules.parcelset.distributed.tcp.nested_vectors_6623|tests.regressions.modules.parcelset.distributed.tcp.very_big_tchunk|tests.regressions.modules.parcelset.distributed.tcp.very_big_parcel|tests.regressions.modules.parcelset.distributed.tcp.very_big_parcel_int_max_plus_1
          - job_name: tests-headers1_1
            artifact_job_name: tests-headers1_1
            run_tests: "true"
            ctest_timeout: "60"
            ctest_jobs: "1"
            ctest_regex: tests.headers.modules.[q-s].*
          - job_name: tests-headers1_2
            artifact_job_name: tests-headers1_2
            run_tests: "true"
            ctest_timeout: "60"
            ctest_jobs: "1"
            ctest_regex: tests.headers.modules.[t-z].*
          - job_name: tests-headers2_1
            artifact_job_name: tests-headers2_1
            run_tests: "true"
            ctest_timeout: "60"
            ctest_jobs: "1"
            ctest_regex: tests.headers.modules.a[a-h].*
          - job_name: tests-headers2_2
            artifact_job_name: tests-headers2_2
            run_tests: "true"
            ctest_timeout: "60"
            ctest_jobs: "1"
            ctest_regex: tests.headers.modules.al.*
          - job_name: tests-headers2_3
            artifact_job_name: tests-headers2_3
            run_tests: "true"
            ctest_timeout: "60"
            ctest_jobs: "1"
            ctest_regex: tests.headers.modules.((a[m-z])|b).*
          - job_name: tests-headers3_1
            artifact_job_name: tests-headers3_1
            run_tests: "true"
            ctest_timeout: "60"
            ctest_jobs: "1"
            ctest_regex: tests.headers.modules.[c-d].*
          - job_name: tests-headers3_2
            artifact_job_name: tests-headers3_2
            run_tests: "true"
            ctest_timeout: "60"
            ctest_jobs: "1"
            ctest_regex: tests.headers.modules.[e-g].*
          - job_name: tests-headers4_1
            artifact_job_name: tests-headers4_1
            run_tests: "true"
            ctest_timeout: "60"
            ctest_jobs: "1"
            ctest_regex: tests.headers.modules.[h-l].*
          - job_name: tests-headers4_2
            artifact_job_name: tests-headers4_2
            run_tests: "true"
            ctest_timeout: "60"
            ctest_jobs: "1"
            ctest_regex: tests.headers.modules.[m-p].*
          - job_name: tests-performance
            artifact_job_name: tests-performance
            build_target: tests.performance
            build_jobs: "2"
            run_tests: "false"
            upload_artifacts: "false"

    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github
          sparse-checkout-cone-mode: false

      - uses: ./.github/actions/hpx-build-and-test
        with:
          build-artifact-name: hpx-build-${{ github.sha }}
          build-target: ${{ matrix.build_target || '' }}
          target-file: ${{ matrix.target_file || '' }}
          build-jobs: ${{ matrix.build_jobs || '2' }}
          run-tests: ${{ matrix.run_tests || 'true' }}
          ctest-timeout: ${{ matrix.ctest_timeout || '180' }}
          ctest-jobs: ${{ matrix.ctest_jobs || '' }}
          ctest-regex: ${{ matrix.ctest_regex || '' }}
          ctest-exclude-regex: ${{ matrix.ctest_exclude_regex || '' }}
          ctest-regex-transform: ${{ matrix.ctest_regex_transform || '' }}
          artifact-job-name: ${{ matrix.artifact_job_name }}
          upload-artifacts: ${{ matrix.upload_artifacts || 'true' }}
